const assert = require('node:assert/strict')
const fs = require('node:fs')
const { test } = require('node:test')

test('API-Football Edge Function handles preflight before auth and shares CORS headers', () => {
  const source = fs.readFileSync(require.resolve('../supabase/functions/api-football-squad/index.ts'), 'utf8')
  assert(source.includes("'https://leedoyoub.github.io'"))
  assert(source.includes("'http://127.0.0.1:5174'"))
  assert(source.includes("'http://localhost:5174'"))
  assert(source.includes("'Access-Control-Allow-Origin'"))
  assert(source.includes("'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info'"))
  assert(source.includes("'Access-Control-Allow-Methods': 'POST, OPTIONS'"))
  const options = source.indexOf("if (request.method === 'OPTIONS')")
  const auth = source.indexOf("const auth = request.headers.get('Authorization')")
  assert(options >= 0 && options < auth)
  assert(source.includes('status: 204, headers: corsHeaders(request)'))
  assert(source.includes('function jsonResponse(request: Request'))
  assert(!source.includes('API_FOOTBALL_KEY:'))
})
