const assert = require('node:assert/strict')
const fs = require('node:fs')
const { test } = require('node:test')
const read = (path) => fs.readFileSync(require.resolve(`../${path}`), 'utf8')

test('shared player avatar preserves uncropped photos and fallback behavior', () => {
  const avatar = read('src/components/PlayerAvatar.tsx')
  assert(avatar.includes('object-contain object-center'))
  assert(avatar.includes('inset-[8%]'))
  assert(avatar.includes('loading="lazy"') && avatar.includes('onError'))
  assert(avatar.includes("showPhoto ? 'bg-white' : 'bg-zinc-700 text-white'"))
  assert(avatar.includes("number ?? '—'"))
})

test('New Player search is explicit, optional, and cannot override the chosen app team', () => {
  const screen = read('src/screens/NewPlayerScreen.tsx')
  assert(screen.includes('Search API Player') && screen.includes('onClick={() => void runSearch()}'))
  assert(screen.includes('if (!user) {') && screen.includes("setApiError('Google sign-in is required"))
  assert(screen.includes('Enter a valid API-Football Player ID.'))
  assert(screen.includes('externalPlayerId: apiSelected.id') && screen.includes('photoUrl: apiSelected.photo'))
  assert(screen.includes('deriveApiPlayerNames(candidate)'))
  assert(screen.includes('teamIds: [...new Set([selectedPlayer.teamId'))
  assert(!screen.includes('currentTeamId'))
})

test('player search is authenticated server-side, uses the supported seasonal partial-name endpoint, and has CORS before auth', () => {
  const helper = read('src/lib/apiFootball.ts'); const edge = read('supabase/functions/api-football-player-search/index.ts')
  assert(helper.includes("functions.invoke('api-football-player-search'"))
  assert(!helper.includes('v3.football.api-sports.io'))
  assert(edge.includes("v3.football.api-sports.io/players/profiles") && edge.includes("url.searchParams.set('player'"))
  assert(edge.indexOf("request.method === 'OPTIONS'") < edge.indexOf("request.headers.get('Authorization')"))
  assert(edge.includes("'Access-Control-Allow-Origin'") && edge.includes("'Access-Control-Allow-Methods': 'POST, OPTIONS'"))
  assert(edge.includes("Deno.env.get('API_FOOTBALL_KEY')"))
  assert(edge.includes('firstname: player.firstname') && edge.includes('lastname: player.lastname'))
  assert(edge.includes("url.searchParams.set('player', String(playerId))"))
  assert(helper.includes('fetchApiFootballPlayer') && helper.includes('externalPlayerId'))
})

test('Player Detail is display-only and sends all player changes through Edit Player', () => {
  const detail = read('src/screens/PlayerDetailScreen.tsx')
  assert(!detail.includes('aria-label="Change player photo"'))
  assert(!detail.includes('Change Photo') && !detail.includes('Remove Photo') && !detail.includes('Use This Photo'))
  assert(detail.includes('<PlayerAvatar photoUrl={player.photoUrl || player.image} number={player.number} className="h-14 w-14 text-sm" />'))
  assert(!detail.includes('Refresh API Name') && !detail.includes('fetchApiFootballPlayer') && !detail.includes('updatePlayer'))
})

test('Edit Player owns the pending, photo-only search flow and commits it through Save', () => {
  const edit = read('src/screens/EditPlayerScreen.tsx')
  assert(edit.includes('Player Photo') && edit.includes('Change Photo') && edit.includes('Remove Photo'))
  assert(edit.includes("searchApiFootballPlayers(trimmed)") && edit.includes('aria-label="Search API player for photo"'))
  assert(edit.includes('setPendingPhotoUrl(photoSelected.photo); setPhotoChanged(true); closePhoto()'))
  assert(edit.includes('setPendingPhotoUrl(undefined); setPhotoChanged(true)'))
  assert(edit.includes('const previewPhotoUrl = photoChanged ? pendingPhotoUrl : player.photoUrl || player.image'))
  assert(edit.includes('...(photoChanged ? { photoUrl: pendingPhotoUrl } : {})'))
  const usePhoto = edit.slice(edit.indexOf('const usePhoto'), edit.indexOf('const removePhoto'))
  assert(!usePhoto.includes('updatePlayer'), 'selecting a photo must not persist before Save')
  assert(!usePhoto.includes('externalPlayerId') && !usePhoto.includes('fullName') && !usePhoto.includes('displayName'))
})

test('Edit Player refreshes only pending names using the linked exact API ID', () => {
  const edit = read('src/screens/EditPlayerScreen.tsx')
  assert(edit.includes("player.externalPlayerId !== undefined &&") && edit.includes('Refresh API Name'))
  assert(edit.includes('fetchApiFootballPlayer(player.externalPlayerId)') && edit.includes('deriveApiPlayerNames(candidate)'))
  assert(edit.includes('setFullName(names.fullName); setDisplayName(names.displayName)'))
  const refresh = edit.slice(edit.indexOf('const refreshApiName'), edit.indexOf('return ('))
  assert(!refresh.includes('updatePlayer'), 'API name refresh must stay pending until Save')
  assert(!refresh.includes('searchApiFootballPlayers'), 'name refresh must not fuzzy-search')
  assert(!refresh.includes('photoUrl') && !refresh.includes('externalPlayerId:'), 'name refresh must not alter identity or photo state')
})

test('standings team identity uses a dedicated link, while TeamIcon remains visual only', () => {
  const link = read('src/components/TeamLink.tsx'); const table = read('src/components/StandingsTable.tsx'); const detail = read('src/screens/TeamDetailScreen.tsx')
  assert(link.includes('onNavigate(team.id)'))
  assert(table.includes('onTeamNavigate ? <TeamLink'))
  assert(detail.includes('<TeamIcon team={team}') && !detail.includes('TeamLink'))
})
