import { useMemo, useState } from 'react'
import { combinationStats, goalPartnerships, onPitchStats, type CombinationKind } from '../engine/analytics'
import { playerDisplayName } from '../components/ui'
import { useStore } from '../store'
import type { View } from '../types'

const CATEGORIES: [CombinationKind | 'goals', string][] = [['duo', 'Duo'], ['attack', 'Attack Unit'], ['midfield', 'Midfield Unit'], ['cb', 'CB Pair'], ['fullback', 'Fullback Pair'], ['backFour', 'Back Four'], ['goals', 'Goal Partnership']]
const labels: Record<CombinationKind, string> = { duo: 'Together', attack: 'Attack unit', midfield: 'Midfield unit', cb: 'CB partnership', fullback: 'Fullback pair', backFour: 'Back four' }

export function ChemistryScreen({ season, onNavigate }: { season: string; onNavigate: (view: View) => void }) {
  const { players, teams, matches } = useStore(); const [category, setCategory] = useState<CombinationKind | 'goals'>('duo'); const [teamId, setTeamId] = useState('')
  const filter = useMemo(() => ({ season, ...(teamId ? { teamId } : {}) }), [season, teamId])
  const combinations = useMemo(() => category === 'goals' ? [] : combinationStats(players, matches, filter, category).filter(row => row.eligible), [players, matches, filter, category])
  const partnerships = useMemo(() => category === 'goals' ? goalPartnerships(players, matches, filter) : [], [players, matches, filter, category])
  const plusMinus = useMemo(() => onPitchStats(players, matches, filter).sort((a, b) => b.plusMinus - a.plusMinus || b.minutes - a.minutes).slice(0, 5), [players, matches, filter])
  const byId = Object.fromEntries(players.map(player => [player.id, player]))
  return <div className="px-4 pb-8 pt-6"><button type="button" onClick={() => onNavigate({ name: 'home' })} className="mb-3 text-xs font-semibold text-emerald-400">← Home</button><div className="mb-4 flex items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Combinations</h1><p className="text-xs text-zinc-400">{season} · actual shared minutes only</p></div><button type="button" onClick={() => onNavigate({ name: 'comparison' })} className="shrink-0 rounded-xl bg-emerald-500 px-3 py-2 text-xs font-black text-black">COMPARE</button></div>
    <select aria-label="Chemistry team filter" value={teamId} onChange={event => setTeamId(event.target.value)} className="mb-3 w-full rounded-xl bg-zinc-900 px-3 py-2 text-xs"><option value="">All teams</option>{teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select>
    <div className="no-scrollbar mb-4 flex gap-2 overflow-x-auto pb-1">{CATEGORIES.map(([id, label]) => <button key={id} type="button" onClick={() => setCategory(id)} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-bold ${category === id ? 'bg-emerald-500 text-black' : 'bg-zinc-900 text-zinc-400'}`}>{label}</button>)}</div>
    {category === 'goals' ? <div className="space-y-2">{partnerships.length === 0 && <Empty />}{partnerships.map(row => <article key={row.key} className="rounded-xl bg-zinc-900 p-3"><p className="text-sm font-bold">{playerDisplayName(byId[row.assisterId])} <span className="text-zinc-500">→</span> {playerDisplayName(byId[row.scorerId])}</p><div className="mt-2 flex items-end justify-between"><span className="text-xs text-zinc-400">Assisted Goals</span><span className="text-xl font-black text-emerald-400">{row.assistedGoals}</span></div></article>)}</div> : <div className="space-y-2">{combinations.length === 0 && <Empty />}{combinations.map(row => <article key={row.key} className="rounded-xl bg-zinc-900 p-3"><p className="truncate text-sm font-bold">{row.playerIds.map(id => playerDisplayName(byId[id])).join(' · ')}</p><div className="mt-2 grid grid-cols-4 gap-2 text-center"><Metric label="Together" value={`${row.togetherMinutes}'`} /><Metric label="Matches" value={String(row.matches)} /><Metric label="GF-GA" value={`${row.goalsFor}-${row.goalsAgainst}`} /><Metric label="GD" value={`${row.goalDifference > 0 ? '+' : ''}${row.goalDifference}`} /></div><p className="mt-2 text-[10px] text-zinc-400">{labels[row.kind]} · G+A {row.combinedGA} · Avg {row.averageRating.toFixed(2)}{row.kind === 'cb' || row.kind === 'backFour' ? ` · GA/90 ${row.togetherMinutes ? (row.goalsAgainst / row.togetherMinutes * 90).toFixed(2) : '0.00'} · CS ${row.cleanSheets}` : ` · W ${row.wins}-${row.draws}-${row.losses}`}</p></article>)}</div>}
    <section className="mt-7"><h2 className="mb-2 text-sm font-semibold">On-pitch +/−</h2><div className="space-y-1.5">{plusMinus.map(row => <div key={`${row.teamId}:${row.playerId}`} className="flex items-center justify-between rounded-xl bg-zinc-900 px-3 py-2 text-xs"><span className="truncate font-semibold">{playerDisplayName(byId[row.playerId])}</span><span className="text-zinc-400">{row.goalsFor}-{row.goalsAgainst}</span><span className={row.plusMinus > 0 ? 'font-black text-emerald-400' : row.plusMinus < 0 ? 'font-black text-red-400' : 'font-black text-zinc-400'}>{row.plusMinus > 0 ? '+' : ''}{row.plusMinus}</span></div>)}</div></section>
  </div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-sm font-black">{value}</p><p className="text-[9px] uppercase text-zinc-500">{label}</p></div> }
function Empty() { return <p className="rounded-xl bg-zinc-900 p-4 text-sm text-zinc-500">No combinations meet the minimum sample: 3 matches or 180 shared minutes.</p> }
