import { useMemo, useState } from 'react'
import { onPitchStats, starterSubstituteSplits } from '../engine/analytics'
import { getMatchManOfTheMatch, matchScore, ratePlayerMatch } from '../engine/rating'
import { matchCompetitionType } from '../engine/competition'
import { buildGlobalRankingData, rankGlobalRankingRows } from '../engine/stats'
import { scopedMetricRanks } from '../engine/seasonAnalytics'
import { playerStreaks } from '../engine/seasonInsights'
import { GOOD_RATING_THRESHOLD } from '../engine/constants'
import { playerFullName } from '../components/ui'
import { useStore } from '../store'
import type { CompetitionType, Match, Player, View } from '../types'

type Direction = 'higher' | 'lower' | 'neutral'
type Summary = { rating: number; last5: number; goals: number; assists: number; combined: number; minutes: number; mom: number; goodMatches: number; streak: string; streakValue: number; overallRank: number | null; positionRank: number | null; teamRank: number | null; starts: number; subs: number; goals90: number; assists90: number; combined90: number; plusMinus: number; wins: number; draws: number; losses: number }
type Metric = { label: string; direction: Direction; value: (summary: Summary) => number | null; display: (value: number | null, summary: Summary) => string }
const fixed = (digits = 2) => (value: number | null) => value === null || !Number.isFinite(value) ? '—' : value.toFixed(digits)
const METRICS: Metric[] = [
  { label: 'Avg Rating', direction: 'higher', value: s => s.rating || null, display: fixed() }, { label: 'Last 5 Avg', direction: 'higher', value: s => s.last5 || null, display: fixed() },
  { label: 'Goals', direction: 'higher', value: s => s.goals, display: fixed(0) }, { label: 'Assists', direction: 'higher', value: s => s.assists, display: fixed(0) }, { label: 'G+A', direction: 'higher', value: s => s.combined, display: fixed(0) }, { label: 'MOM', direction: 'higher', value: s => s.mom, display: fixed(0) },
  { label: 'Minutes', direction: 'neutral', value: s => s.minutes, display: fixed(0) }, { label: `${GOOD_RATING_THRESHOLD}+ Matches`, direction: 'higher', value: s => s.goodMatches, display: fixed(0) }, { label: 'Active Streak', direction: 'higher', value: s => s.streakValue, display: (_value, s) => s.streak },
  { label: 'Overall Rank', direction: 'lower', value: s => s.overallRank, display: value => value ? `#${value}` : '—' }, { label: 'Position Rank', direction: 'lower', value: s => s.positionRank, display: value => value ? `#${value}` : '—' }, { label: 'Team Rank', direction: 'lower', value: s => s.teamRank, display: value => value ? `#${value}` : '—' },
  { label: 'Starts', direction: 'neutral', value: s => s.starts, display: fixed(0) }, { label: 'Sub Apps', direction: 'neutral', value: s => s.subs, display: fixed(0) }, { label: 'Goals/90', direction: 'higher', value: s => s.goals90, display: fixed() }, { label: 'Assists/90', direction: 'higher', value: s => s.assists90, display: fixed() }, { label: 'G+A/90', direction: 'higher', value: s => s.combined90, display: fixed() }, { label: 'On-pitch +/-', direction: 'higher', value: s => s.plusMinus, display: value => value === null ? '—' : `${value > 0 ? '+' : ''}${value}` }, { label: 'W-D-L', direction: 'neutral', value: () => null, display: (_value, s) => `${s.wins}-${s.draws}-${s.losses}` },
]

export function ComparisonScreen({ season, initialLeftId, initialRightId, initialCompetition = 'all', onNavigate }: { season: string; initialLeftId?: string; initialRightId?: string; initialCompetition?: CompetitionType | 'all'; onNavigate: (view: View) => void }) {
  const { players, teams, matches } = useStore(); const [teamId, setTeamId] = useState(''); const [competition, setCompetition] = useState<CompetitionType | 'all'>(initialCompetition); const [leftId, setLeftId] = useState(initialLeftId ?? players[0]?.id ?? ''); const [rightId, setRightId] = useState(initialRightId ?? players[1]?.id ?? players[0]?.id ?? '')
  const filter = useMemo(() => ({ season, competition, ...(teamId ? { teamId } : {}) }), [season, competition, teamId]); const left = players.find(player => player.id === leftId); const right = players.find(player => player.id === rightId)
  const scoped = useMemo(() => matches.filter(match => match.season === season && (competition === 'all' || matchCompetitionType(match) === competition)), [matches, season, competition])
  const rankingIndex = useMemo(() => buildGlobalRankingData(players, scoped, { seasons: [season], teams: teamId ? [teamId] : [], positions: [] }, 'rating'), [players, scoped, season, teamId]); const ranking = useMemo(() => rankGlobalRankingRows(rankingIndex, players, 'rating'), [rankingIndex, players])
  const summaries = useMemo(() => new Map([left, right].filter((player): player is Player => Boolean(player)).map(player => [player.id, summary(player, players, scoped, filter, ranking)])), [left, right, players, scoped, filter, ranking])
  return <div className="px-4 pb-8 pt-6"><button type="button" onClick={() => onNavigate({ name: 'competition', season, competitionType: competition === 'all' ? 'league' : competition })} className="mb-3 text-xs font-semibold text-emerald-400">Rankings</button><h1 className="text-2xl font-semibold">Player Comparison</h1><p className="mb-4 text-xs text-zinc-400">{season} · values are visually emphasized only where the metric has a meaningful direction</p><div className="mb-3 grid grid-cols-2 gap-2"><select aria-label="Comparison competition filter" value={competition} onChange={event => setCompetition(event.target.value as CompetitionType | 'all')} className="w-full rounded-xl bg-zinc-900 p-2 text-xs"><option value="all">All competitions</option><option value="league">League</option><option value="cup">Cup</option><option value="champions">Champions</option></select><select aria-label="Comparison team filter" value={teamId} onChange={event => setTeamId(event.target.value)} className="w-full rounded-xl bg-zinc-900 p-2 text-xs"><option value="">All teams</option>{teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div><div className="mb-4 grid grid-cols-2 gap-2"><PlayerSelect label="Left player" value={leftId} players={players} onChange={setLeftId} /><PlayerSelect label="Right player" value={rightId} players={players} onChange={setRightId} /></div><div className="overflow-hidden rounded-xl bg-zinc-900"><div className="grid grid-cols-[1fr_auto_1fr] gap-2 border-b border-white/10 px-3 py-3 text-center text-xs font-bold"><span className="truncate">{left ? playerFullName(left) : 'Select player'}</span><span className="text-zinc-600">vs</span><span className="truncate">{right ? playerFullName(right) : 'Select player'}</span></div>{METRICS.map(metric => { const leftSummary = left ? summaries.get(left.id) : undefined; const rightSummary = right ? summaries.get(right.id) : undefined; const leftValue = leftSummary ? metric.value(leftSummary) : null; const rightValue = rightSummary ? metric.value(rightSummary) : null; return <div key={metric.label} className="grid grid-cols-[1fr_auto_1fr] gap-2 border-b border-white/[.06] px-3 py-2 text-center text-xs last:border-0"><ComparisonValue metric={metric} value={leftValue} other={rightValue} text={leftSummary ? metric.display(leftValue, leftSummary) : '—'} /><span className="text-zinc-500">{metric.label}</span><ComparisonValue metric={metric} value={rightValue} other={leftValue} text={rightSummary ? metric.display(rightValue, rightSummary) : '—'} /></div>})}</div></div>
}
function ComparisonValue({ metric, value, other, text }: { metric: Metric; value: number | null; other: number | null; text: string }) { const rounded = (item: number | null) => item === null ? null : Number(item.toFixed(2)); const current = rounded(value); const opponent = rounded(other); const better = current !== null && opponent !== null && (metric.direction === 'higher' ? current > opponent : metric.direction === 'lower' ? current < opponent : false); return <span aria-label={`${metric.label}: ${text}${better ? ', better value' : ''}`} className={better ? 'font-black text-emerald-300' : 'text-zinc-200'}>{text}</span> }
function PlayerSelect({ label, value, players, onChange }: { label: string; value: string; players: Player[]; onChange: (value: string) => void }) { return <label className="text-[10px] text-zinc-400">{label}<select aria-label={label} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-xl bg-zinc-900 p-2 text-xs text-white">{players.map(player => <option key={player.id} value={player.id}>{playerFullName(player)}</option>)}</select></label> }
function summary(player: Player, allPlayers: Player[], matches: Match[], filter: { season: string; competition: CompetitionType | 'all'; teamId?: string }, ranking: ReturnType<typeof rankGlobalRankingRows>): Summary { const scoped = matches.filter(match => !filter.teamId || match.appearances.some(appearance => appearance.playerId === player.id && appearance.teamId === filter.teamId)); const roles = starterSubstituteSplits(player, scoped, filter); const rows = [roles.starter, roles.substitute]; const minutes = rows.reduce((total, row) => total + row.minutes, 0); const goals = rows.reduce((total, row) => total + row.goals, 0); const assists = rows.reduce((total, row) => total + row.assists, 0); const apps = rows.reduce((total, row) => total + row.apps, 0); const rating = apps ? rows.reduce((total, row) => total + row.averageRating * row.apps, 0) / apps : 0; const onPitch = onPitchStats([player], scoped, filter).reduce((total, row) => total + row.plusMinus, 0); let wins = 0; let draws = 0; let losses = 0; for (const match of scoped) { const appearance = match.appearances.find(item => item.playerId === player.id && (!filter.teamId || item.teamId === filter.teamId)); if (!appearance || !ratePlayerMatch(match, player)) continue; const score = matchScore(match); const ours = appearance.teamId === match.homeTeamId ? score.home : score.away; const theirs = appearance.teamId === match.homeTeamId ? score.away : score.home; if (ours > theirs) wins++; else if (ours === theirs) draws++; else losses++ }; const rated = scoped.flatMap(match => { const row = ratePlayerMatch(match, player); return row ? [row] : [] }); const recent = rated.slice(-5); const last5 = recent.length ? recent.reduce((sum, row) => sum + row.raw, 0) / recent.length : 0; const active = playerStreaks(player, scoped).filter(row => row.current > 1).sort((a, b) => b.current - a.current)[0]; const ranks = scopedMetricRanks(ranking, allPlayers, player.id); return { rating, last5, goals, assists, combined: goals + assists, minutes, mom: scoped.filter(match => getMatchManOfTheMatch(match, allPlayers) === player.id).length, goodMatches: rated.filter(row => row.raw >= GOOD_RATING_THRESHOLD).length, streak: active ? `${active.current} straight · ${active.label}` : 'No active streak', streakValue: active?.current ?? 0, overallRank: ranks.overall, positionRank: ranks.position, teamRank: ranks.team, starts: roles.starter.apps, subs: roles.substitute.apps, goals90: minutes ? goals / minutes * 90 : 0, assists90: minutes ? assists / minutes * 90 : 0, combined90: minutes ? (goals + assists) / minutes * 90 : 0, plusMinus: onPitch, wins, draws, losses } }
