import { useMemo, useState } from 'react'
import { onPitchStats, starterSubstituteSplits } from '../engine/analytics'
import { getMatchManOfTheMatch, matchScore, ratePlayerMatch } from '../engine/rating'
import { playerFullName } from '../components/ui'
import { useStore } from '../store'
import type { Match, Player, View } from '../types'

type Summary = { rating: number; goals: number; assists: number; combined: number; minutes: number; mom: number; starts: number; subs: number; goals90: number; assists90: number; combined90: number; plusMinus: number; wins: number; draws: number; losses: number }
export function ComparisonScreen({ season, onNavigate }: { season: string; onNavigate: (view: View) => void }) {
  const { players, teams, matches } = useStore(); const [teamId, setTeamId] = useState(''); const [leftId, setLeftId] = useState(players[0]?.id ?? ''); const [rightId, setRightId] = useState(players[1]?.id ?? players[0]?.id ?? '')
  const filter = useMemo(() => ({ season, ...(teamId ? { teamId } : {}) }), [season, teamId]); const left = players.find(player => player.id === leftId); const right = players.find(player => player.id === rightId)
  const summaries = useMemo(() => new Map([left, right].filter((player): player is Player => Boolean(player)).map(player => [player.id, summary(player, players, matches, filter)])), [left, right, players, matches, filter])
  const rows: [string, (summary: Summary) => string][] = [['Rating', s => s.rating ? s.rating.toFixed(2) : '—'], ['Goals', s => String(s.goals)], ['Assists', s => String(s.assists)], ['G+A', s => String(s.combined)], ['Minutes', s => String(s.minutes)], ['MOM', s => String(s.mom)], ['Starts', s => String(s.starts)], ['Sub Apps', s => String(s.subs)], ['Goals/90', s => s.goals90.toFixed(2)], ['Assists/90', s => s.assists90.toFixed(2)], ['G+A/90', s => s.combined90.toFixed(2)], ['On-pitch +/-', s => `${s.plusMinus > 0 ? '+' : ''}${s.plusMinus}`], ['W-D-L', s => `${s.wins}-${s.draws}-${s.losses}`]]
  return <div className="px-4 pb-8 pt-6"><button type="button" onClick={() => onNavigate({ name: 'chemistry' })} className="mb-3 text-xs font-semibold text-emerald-400">← Combinations</button><h1 className="text-2xl font-semibold">Player Comparison</h1><p className="mb-4 text-xs text-zinc-400">{season}</p><select aria-label="Comparison team filter" value={teamId} onChange={event => setTeamId(event.target.value)} className="mb-3 w-full rounded-xl bg-zinc-900 p-2 text-xs"><option value="">All teams</option>{teams.map(team => <option key={team.id} value={team.id}>{team.name}</option>)}</select><div className="mb-4 grid grid-cols-2 gap-2"><PlayerSelect label="Left player" value={leftId} players={players} onChange={setLeftId} /><PlayerSelect label="Right player" value={rightId} players={players} onChange={setRightId} /></div><div className="overflow-hidden rounded-xl bg-zinc-900"><div className="grid grid-cols-[1fr_auto_1fr] gap-2 border-b border-white/10 px-3 py-3 text-center text-xs font-bold"><span className="truncate">{left ? playerFullName(left) : 'Select player'}</span><span className="text-zinc-600">vs</span><span className="truncate">{right ? playerFullName(right) : 'Select player'}</span></div>{rows.map(([label, value]) => <div key={label} className="grid grid-cols-[1fr_auto_1fr] gap-2 border-b border-white/[.06] px-3 py-2 text-center text-xs last:border-0"><span>{left ? value(summaries.get(left.id)!) : '—'}</span><span className="text-zinc-500">{label}</span><span>{right ? value(summaries.get(right.id)!) : '—'}</span></div>)}</div></div>
}
function PlayerSelect({ label, value, players, onChange }: { label: string; value: string; players: Player[]; onChange: (value: string) => void }) { return <label className="text-[10px] text-zinc-400">{label}<select aria-label={label} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-xl bg-zinc-900 p-2 text-xs text-white">{players.map(player => <option key={player.id} value={player.id}>{playerFullName(player)}</option>)}</select></label> }
function summary(player: Player, allPlayers: Player[], matches: Match[], filter: { season: string; teamId?: string }): Summary {
  const scoped = matches.filter(match => match.season === filter.season && (!filter.teamId || match.appearances.some(appearance => appearance.playerId === player.id && appearance.teamId === filter.teamId)))
  const roles = starterSubstituteSplits(player, scoped, filter); const all = [roles.starter, roles.substitute]; const minutes = all.reduce((total, row) => total + row.minutes, 0); const goals = all.reduce((total, row) => total + row.goals, 0); const assists = all.reduce((total, row) => total + row.assists, 0); const apps = all.reduce((total, row) => total + row.apps, 0); const rating = apps ? all.reduce((total, row) => total + row.averageRating * row.apps, 0) / apps : 0
  const onPitch = onPitchStats([player], scoped, filter).reduce((total, row) => total + row.plusMinus, 0); let wins = 0; let draws = 0; let losses = 0
  for (const match of scoped) { const appearance = match.appearances.find(item => item.playerId === player.id && (!filter.teamId || item.teamId === filter.teamId)); if (!appearance || !ratePlayerMatch(match, player)) continue; const score = matchScore(match); const ours = appearance.teamId === match.homeTeamId ? score.home : score.away; const theirs = appearance.teamId === match.homeTeamId ? score.away : score.home; if (ours > theirs) wins++; else if (ours === theirs) draws++; else losses++ }
  return { rating, goals, assists, combined: goals + assists, minutes, mom: scoped.filter(match => getMatchManOfTheMatch(match, allPlayers) === player.id).length, starts: roles.starter.apps, subs: roles.substitute.apps, goals90: minutes ? goals / minutes * 90 : 0, assists90: minutes ? assists / minutes * 90 : 0, combined90: minutes ? (goals + assists) / minutes * 90 : 0, plusMinus: onPitch, wins, draws, losses }
}
