import { useMemo, type ReactNode } from 'react'
import { APP_VERSION } from '../config'
import { PlayerIdentityAction, TeamIdentityAction } from '../components/EntityActions'
import { SectionHeader } from '../components/SeasonUI'
import { RankingMetricTabs, RankingRow, useMetricSwipe } from '../components/RankingRow'
import { RANKING_METRICS, formatRankingMetricValue, type RankingDisplayMetric } from '../lib/rankingMetrics'
import { deriveLatestChanges } from '../engine/latestChanges'
import { buildGlobalRankingData, rankGlobalRankingRows } from '../engine/stats'
import { positionFilterFamilies } from '../engine/positionScope'
import { PositionFilter } from '../components/PositionFilter'
import { competitionRevision } from '../engine/competitionRevision'
import { selectChampionsCompetition, selectCupCompetition, selectLeagueCompetition } from '../engine/competitionSelectors'
import { competitionProgressLabels, formatChampionsStage, formatCupProgress, formatLeagueProgress } from '../lib/competitionProgressPresentation'
import { seasonAwards } from '../engine/awards'
import { AwardBestXI } from '../components/AwardBestXI'
import { matchCompetitionType } from '../engine/competitionContext'
import { recentDerivedResults } from '../lib/results'
import { resultTone } from '../lib/resultTone'
import { useStore } from '../store'
import type { Player, ScreenStateByView, Team, View } from '../types'

const FALLBACK_COMPETITION_CACHE_OWNER = {}

export function HomeScreen({ season, screenState, onStateChange, onNavigate }: { season: string; screenState: ScreenStateByView['home']; onStateChange: (state: ScreenStateByView['home']) => void; onSeason?: (season: string) => void; onNavigate: (view: View) => void }) {
  const { players, teams, matches, competitionStates = [], competitionRevisions = {}, competitionCacheOwner: storeCompetitionCacheOwner, teamCatalogRevision = 0 } = useStore()
  const competitionCacheOwner = storeCompetitionCacheOwner ?? FALLBACK_COMPETITION_CACHE_OWNER
  const metric = screenState.leaderMetric as RankingDisplayMetric
  const recent = useMemo(() => recentDerivedResults(matches, teams, 5), [matches, teams])
  const latestChanges = useMemo(() => deriveLatestChanges(players, teams, matches, competitionStates, season), [players, teams, matches, competitionStates, season])
  const seasonMatches = useMemo(() => matches.filter(match => match.season === season), [matches, season])
  const rankingIndex = useMemo(() => buildGlobalRankingData(players, seasonMatches, { seasons: [season], teams: [], positions: positionFilterFamilies(screenState.positionFilter) }, 'rating'), [players, seasonMatches, season, screenState.positionFilter])
  const leaderRows = useMemo(() => rankGlobalRankingRows(rankingIndex, players, metric).slice(0, 10), [rankingIndex, players, metric])
  const playerById = useMemo(() => Object.fromEntries(players.map(player => [player.id, player])) as Record<string, Player>, [players]); const teamById = useMemo(() => Object.fromEntries(teams.map(team => [team.id, team])) as Record<string, Team>, [teams])
  const leagueRevision = competitionRevision(competitionRevisions, season, 'league')
  const cupRevision = competitionRevision(competitionRevisions, season, 'cup')
  const championsRevision = competitionRevision(competitionRevisions, season, 'champions')
  const championsDraw = competitionStates.find(state => state.id === `champions:${season}`)
  const league = useMemo(() => selectLeagueCompetition(competitionCacheOwner, teams, matches, season, leagueRevision, teamCatalogRevision, undefined, players), [competitionCacheOwner, teams, matches, season, leagueRevision, teamCatalogRevision, players])
  const cup = useMemo(() => selectCupCompetition(competitionCacheOwner, teams, matches, season, cupRevision, teamCatalogRevision, players), [competitionCacheOwner, teams, matches, season, cupRevision, teamCatalogRevision, players])
  const champions = useMemo(() => selectChampionsCompetition(competitionCacheOwner, championsDraw, matches, season, championsRevision, players), [competitionCacheOwner, championsDraw, matches, season, championsRevision, players])
  const seasonBestXI = useMemo(() => seasonAwards(season, teams, players, matches, competitionStates), [season, teams, players, matches, competitionStates])
  const progressLabels = competitionProgressLabels()
  const selectMetric = (next: RankingDisplayMetric) => onStateChange({ ...screenState, leaderMetric: next })
  const leaderSwipe = useMetricSwipe(RANKING_METRICS.map(item => item.value), metric, selectMetric)
  return <div className="px-4 pb-8 pt-6">
    <header className="mb-5 rounded-2xl border border-white/5 bg-zinc-900 p-3"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-400">Season dashboard</p><div className="mt-1 flex items-baseline justify-between gap-3"><h1 className="text-xl font-semibold">{season}</h1><span className="text-xs text-zinc-400">Competition progress</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px]"><Snapshot label={progressLabels.league} value={formatLeagueProgress(league)} /><Snapshot label={progressLabels.cup} value={formatCupProgress({ complete: Boolean(cup.championId), stage: cup.stage })} /><Snapshot label={progressLabels.champions} value={champions.championId ? "Completed" : champions.drawn ? formatChampionsStage(champions.currentStage) : "Not started"} /></div></header>
    <section className="mb-6" data-home-section="recent-matches"><SectionHeader title="Recent Matches" action={matches.length > 5 ? <button type="button" onClick={() => onNavigate({ name: 'results' })} className="secondary-view-all">View All</button> : undefined} /><div className="mt-2 grid grid-cols-5 gap-1.5" aria-label="Latest five recent matches">{recent.length ? recent.map(result => { const type = matchCompetitionType(result.match); const competition = type === 'champions' ? 'Champions' : type === 'cup' ? 'Cup' : 'League'; const tone = resultTone(result.outcome); return <div key={result.match.id} className={`flex min-h-20 min-w-0 flex-col items-center justify-between rounded-xl border px-1 py-2 text-center ${tone}`}><span className="text-[8px] font-black tracking-wide text-zinc-300">{competition}</span><TeamIdentityAction team={teamById[result.teamId]} onNavigate={id => onNavigate({ name: 'team', id })} iconClassName="h-7 w-7 text-[7px]" /><button type="button" onClick={() => onNavigate({ name: 'match', id: result.match.id })} aria-label={`${competition}, ${result.outcome === 'W' ? 'win' : result.outcome === 'L' ? 'loss' : 'draw'}, ${result.goalsFor} to ${result.goalsAgainst}`} className="rounded-md px-1 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-300"><b className="text-xs tabular-nums">{result.goalsFor}–{result.goalsAgainst}</b></button></div> }) : <div className="col-span-5"><Empty text="No completed matches yet." /></div>}</div></section>
    <section className="mb-6" data-home-section="latest-changes"><SectionHeader title="Latest Changes" action={latestChanges.length ? <button type="button" onClick={() => onNavigate({ name: 'latest-changes', season })} className="secondary-view-all">View All</button> : undefined} /><div className="mt-2 space-y-1.5">{latestChanges.slice(0, 4).map(group => <LatestChangeCard key={group.id} group={group} players={playerById} teams={teamById} onNavigate={onNavigate} />)}{!latestChanges.length && <Empty text="Meaningful changes will appear as the season develops." />}</div></section>
    <section data-home-section="season-leaders"><SectionHeader title="Global Ranking" subtitle="Top 10 · All Competitions" action={<button type="button" onClick={() => onNavigate({ name: 'global-ranking', season, competitionType: 'all', rankingMetric: metric })} className="secondary-view-all">View All</button>} /><div className="mt-2 flex justify-end"><PositionFilter value={screenState.positionFilter} onChange={positionFilter => onStateChange({ ...screenState, positionFilter })} label="Global Ranking position" /></div><div className="mt-2"><RankingMetricTabs label="Global ranking category" value={metric} onChange={selectMetric} options={RANKING_METRICS} /></div><div {...leaderSwipe} className="mt-2 overflow-hidden rounded-xl bg-zinc-900 touch-pan-y" aria-label="Swipe Global Ranking metrics">{leaderRows.slice(0, 10).map((row, index) => { const player = playerById[row.playerId]; const team = teamById[row.historicalTeamId ?? row.teamId]; return <div key={row.playerId} className="border-b border-white/5 last:border-0"><RankingRow rank={index + 1} compact player={player} team={team} value={formatRankingMetricValue(metric, row.value)} onPlayerNavigate={id => onNavigate({ name: 'player', id })} onTeamNavigate={id => onNavigate({ name: 'team', id })} /></div>})}{!leaderRows.length && <p className="p-3 text-xs text-zinc-500">No qualifying players yet.</p>}</div></section>
    <section className="mb-6" data-home-section="season-best-xi"><AwardBestXI title="Season Best XI" result={{ bestXI: seasonBestXI.bestXI, statsByPlayer: seasonBestXI.statsByPlayer, bestPlayerId: seasonBestXI.bestPlayerId }} players={players} teams={teams} onPlayerOpen={id => onNavigate({ name: 'player', id })} /></section>
    <footer className="mt-6 text-center text-[10px] text-zinc-600">Football Tracker · v{APP_VERSION} · <button type="button" onClick={() => onNavigate({ name: 'data-management' })} className="underline">Manage data</button></footer>
  </div>
}
function Snapshot({ label, value, icon }: { label: string; value: string; icon?: ReactNode }) { return <div className="min-w-0 rounded-xl bg-black/20 px-2 py-2"><small className="block uppercase text-zinc-500">{label}</small><span className="mt-1 flex min-w-0 items-center gap-1 font-bold">{icon}<b className="truncate">{value}</b></span></div> }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-zinc-900 p-3 text-xs text-zinc-500">{text}</p> }
function LatestChangeCard({ group, players, teams, onNavigate }: { group: ReturnType<typeof deriveLatestChanges>[number]; players: Record<string, Player>; teams: Record<string, Team>; onNavigate: (view: View) => void }) { const item = group.items[0]; return <article className="rounded-xl bg-zinc-900 px-3 py-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-[9px] font-black uppercase text-emerald-300">{item.emoji} {item.category}</p><p className="mt-1 text-xs font-bold">{group.title}</p><p className="mt-1 text-[10px] text-zinc-500">{group.detail}</p></div>{group.matchId && <button type="button" onClick={() => onNavigate({ name: 'match', id: group.matchId! })} className="shrink-0 rounded-md text-[10px] text-emerald-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-300">Match</button>}</div><div className="mt-2 flex gap-2">{group.playerIds.map(id => <TeamOrPlayer key={`p:${id}`} player={players[id]} onNavigate={onNavigate} />)}{group.teamIds.map(id => <TeamOrPlayer key={`t:${id}`} team={teams[id]} onNavigate={onNavigate} />)}</div></article> }
function TeamOrPlayer({ player, team, onNavigate }: { player?: Player; team?: Team; onNavigate: (view: View) => void }) { return player ? <PlayerIdentityAction player={player} onNavigate={id => onNavigate({ name: 'player', id })} className="truncate text-[10px] text-zinc-300" avatarClassName="hidden">{player.displayName ?? player.name}</PlayerIdentityAction> : team ? <TeamIdentityAction team={team} onNavigate={id => onNavigate({ name: 'team', id })} className="truncate text-[10px] text-zinc-300">{team.shortName}</TeamIdentityAction> : null }
