import { useMemo, useState } from 'react'
import { ResultCard } from '../components/ResultCard'
import { deriveNews, type NewsKind } from '../engine/news'
import { derivedResults } from '../lib/results'
import { useStore } from '../store'
import type { View } from '../types'
const labels: Record<NewsKind, string> = { player: 'Player News', match: 'Match Stories', team: 'Team News' }
export function NewsScreen({ season, kind, onNavigate }: { season: string; kind?: NewsKind; onNavigate: (view: View) => void }) {
  const { players, teams, matches } = useStore(); const [expanded, setExpanded] = useState<NewsKind | undefined>(kind); const [limit, setLimit] = useState(20)
  const items = useMemo(() => deriveNews(players, teams, matches.filter(match => match.season === season)), [players, teams, matches, season]); const results = useMemo(() => derivedResults(matches, teams), [matches, teams])
  const section = (type: NewsKind) => { const rows = items.filter(item => item.kind === type); const visible = expanded === type ? rows.slice(0, limit) : rows.slice(0, 5); return <section key={type} className="mb-6"><div className="mb-2 flex items-end justify-between"><div><h2 className="text-lg font-semibold">{labels[type]}</h2><p className="text-xs text-zinc-500">Derived from saved matches</p></div>{expanded !== type && rows.length > 5 && <button type="button" onClick={() => { setExpanded(type); setLimit(20) }} className="secondary-view-all">View All</button>}</div><div className="space-y-2">{visible.length ? visible.map(item => <button key={item.id} type="button" onClick={() => item.matchId && onNavigate({ name: 'match', id: item.matchId })} className="w-full rounded-xl border border-white/5 bg-zinc-900 p-3 text-left"><p className="text-[10px] font-black uppercase tracking-wide text-emerald-400">{item.eyebrow}</p><p className="mt-1 text-sm font-bold">{item.title}</p><p className="mt-1 text-xs text-zinc-400">{item.detail}</p><p className="mt-2 text-[10px] text-zinc-500">{item.context}</p></button>) : <p className="rounded-xl bg-zinc-900 p-3 text-xs text-zinc-500">No stories yet.</p>}</div>{expanded === type && visible.length < rows.length && <button type="button" onClick={() => setLimit(value => value + 20)} className="mt-3 w-full rounded-xl bg-zinc-900 py-2 text-xs font-bold text-emerald-400">Load more</button>}</section> }
  return <div className="px-4 pb-8 pt-6"><h1 className="mb-1 text-2xl font-semibold">News</h1><p className="mb-5 text-xs text-zinc-400">{season} · stories from your match history</p>{!expanded && <section className="mb-6"><div className="mb-2 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Recent Results</h2><p className="text-xs text-zinc-500">All tracked teams</p></div>{results.length > 5 && <button type="button" onClick={() => onNavigate({ name: 'results' })} className="secondary-view-all">View All</button>}</div><div className="space-y-2">{results.length ? results.slice(0, 5).map(result => <ResultCard key={result.match.id} result={result} teams={teams} onClick={() => onNavigate({ name: 'match', id: result.match.id })} />) : <p className="rounded-xl bg-zinc-900 p-3 text-xs text-zinc-500">No match results yet.</p>}</div></section>}{expanded ? <><button type="button" onClick={() => setExpanded(undefined)} className="mb-4 text-xs font-semibold text-emerald-400">Back to all news</button>{section(expanded)}</> : (['player', 'match', 'team'] as NewsKind[]).map(section)}</div>
}
