import { useState } from 'react'
import { recentMatches, recentMatchPositions } from './recentMatches'
import { playerFullName, AssistIcon, formatDate, GoalIcon, ratingTone } from '../components/ui'
import { TeamIcon } from '../components/TeamIcon'
import { PlayerAvatar } from '../components/PlayerAvatar'
import { matchScore, ratePlayerMatch, getMatchManOfTheMatch } from '../engine/rating'
import { playerSeasonStats, seasonsFromMatches } from '../engine/stats'
import { onPitchStats, positionSplits, starterSubstituteSplits } from '../engine/analytics'
import { playerForm, playerStreaks } from '../engine/seasonInsights'
import { useStore } from '../store'
import type { Match, View } from '../types'
import { fetchApiFootballPlayer, searchApiFootballPlayers, type ApiFootballPlayerSearchResult } from '../lib/apiFootball'
import { deriveApiPlayerNames } from '../lib/playerNames'
import { useAuth } from '../lib/auth'

function ResultPill({ match, teamId }: { match: Match; teamId: string }) {
  const score = matchScore(match); const ours = match.homeTeamId === teamId ? score.home : score.away; const theirs = match.homeTeamId === teamId ? score.away : score.home
  const result = ours > theirs ? 'WIN' : ours === theirs ? 'DRAW' : 'LOSS'
  return <span className={`text-[10px] font-black ${result === 'WIN' ? 'text-emerald-400' : result === 'DRAW' ? 'text-yellow-400' : 'text-red-400'}`}>{result}</span>
}

export function PlayerDetailScreen({ playerId, season, onNavigate, onBack }: { playerId: string; season: string; onNavigate: (view: View) => void; onBack: () => void }) {
  const { players, teams, matches, updatePlayer } = useStore(); const { user } = useAuth(); const player = players.find(item => item.id === playerId)
  const seasons = seasonsFromMatches(matches); const active = seasons.includes(season) ? season : seasons[0] ?? season
  const recordedTeamIds = [...new Set(matches.filter(match => match.season === active).flatMap(match => match.appearances.filter(appearance => appearance.playerId === player?.id).map(appearance => appearance.teamId)))]
  const [selectedTeamIds, setSelectedTeamIds] = useState<string[]>(recordedTeamIds)
  const [photoOpen, setPhotoOpen] = useState(false); const [photoQuery, setPhotoQuery] = useState(''); const [photoResults, setPhotoResults] = useState<ApiFootballPlayerSearchResult[]>([]); const [photoSelected, setPhotoSelected] = useState<ApiFootballPlayerSearchResult | null>(null); const [photoLoading, setPhotoLoading] = useState(false); const [photoError, setPhotoError] = useState(''); const [nameLoading, setNameLoading] = useState(false); const [nameMessage, setNameMessage] = useState('')
  const statsBase = player ? playerSeasonStats(player, players, matches, active) : null
  if (!player || !statsBase) return <div className="p-6 text-sm text-zinc-400">Player not found.</div>
  const selected = selectedTeamIds.length ? selectedTeamIds : recordedTeamIds
  const records = recentMatches(matches.filter(match => match.season === active && match.appearances.some(appearance => appearance.playerId === player.id && selected.includes(appearance.teamId))))
  const rated = records.flatMap(match => { const rating = ratePlayerMatch(match, player); const appearance = match.appearances.find(item => item.playerId === player.id); return rating && appearance ? [{ match, rating, appearance }] : [] })
  const goals = records.reduce((total, match) => total + match.events.filter(event => event.type === 'goal' && !event.ownGoal && event.playerId === player.id).length, 0)
  const assists = records.reduce((total, match) => total + match.events.filter(event => event.type === 'goal' && !event.ownGoal && event.assistPlayerId === player.id).length, 0)
  const average = rated.length ? rated.reduce((total, item) => total + item.rating.raw, 0) / rated.length : 0
  const form = playerForm(player, records); const streaks = playerStreaks(player, records)
  const splitFilter = { season: active }; const positions = positionSplits(player, records, splitFilter); const roles = starterSubstituteSplits(player, records, splitFilter)
  const onPitch = onPitchStats([player], records, splitFilter).reduce((total, row) => ({ goalsFor: total.goalsFor + row.goalsFor, goalsAgainst: total.goalsAgainst + row.goalsAgainst, plusMinus: total.plusMinus + row.plusMinus }), { goalsFor: 0, goalsAgainst: 0, plusMinus: 0 })
  const closePhoto = () => { setPhotoOpen(false); setPhotoSelected(null); setPhotoResults([]); setPhotoError('') }
  const searchPhotos = async () => { const query = photoQuery.trim(); if (!user) { setPhotoError('Google sign-in is required for API player search.'); return }; if (query.length < 3) { setPhotoError('Enter at least 3 characters to search.'); return }; setPhotoLoading(true); setPhotoError(''); setPhotoResults([]); try { const results = await searchApiFootballPlayers(query); setPhotoResults(results); if (!results.length) setPhotoError('No matching API players found.') } catch (error) { setPhotoError(error instanceof Error ? error.message : 'Could not search players. Try again later.') } finally { setPhotoLoading(false) } }
  const usePhoto = () => { if (!photoSelected?.photo) return; updatePlayer(player.id, { photoUrl: photoSelected.photo }); closePhoto() }
  const removePhoto = () => { updatePlayer(player.id, { photoUrl: undefined }); closePhoto() }
  const refreshApiName = async () => { if (player.externalPlayerId === undefined) return; setNameLoading(true); setNameMessage(''); try { const candidate = await fetchApiFootballPlayer(player.externalPlayerId); const names = deriveApiPlayerNames(candidate); updatePlayer(player.id, { fullName: names.fullName, displayName: names.displayName }); setNameMessage('Name updated from the linked API profile.') } catch (error) { setNameMessage(error instanceof Error ? error.message : 'Could not refresh API name.') } finally { setNameLoading(false) } }
  return <div className="px-4 pb-8 pt-6">
    <button type="button" onClick={onBack} className="mb-3 text-xs font-semibold text-emerald-400">Back</button>
    <div className="mb-4 flex items-start gap-3"><button type="button" aria-label="Change photo" onClick={() => setPhotoOpen(true)} className="relative shrink-0 rounded-full focus:outline-none focus:ring-2 focus:ring-emerald-400"><PlayerAvatar photoUrl={player.photoUrl || player.image} number={player.number} className="h-14 w-14 text-sm" /><span className="absolute -bottom-1 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-zinc-800 px-1.5 py-0.5 text-[8px] font-bold text-zinc-200">Change</span></button><div className="min-w-0 flex-1"><p className="text-xs text-zinc-400">{player.teamId ? teams.find(team => team.id === player.teamId)?.name : 'No Team'} · #{player.number} · {player.position}</p><h1 className="break-words text-2xl font-semibold">{playerFullName(player)}</h1><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={() => onNavigate({ name: 'edit-player', id: player.id })} className="rounded-full bg-zinc-800 px-3 py-1.5 text-xs font-bold">Edit player</button>{player.externalPlayerId !== undefined && <button type="button" disabled={nameLoading} onClick={() => void refreshApiName()} className="rounded-full bg-zinc-800 px-3 py-1.5 text-xs font-bold disabled:opacity-40">{nameLoading ? 'Refreshing…' : 'Refresh API Name'}</button>}</div>{nameMessage && <p role="status" className="mt-2 text-xs text-zinc-400">{nameMessage}</p>}</div></div>
    {photoOpen && <div role="dialog" aria-modal="true" aria-label="Change Photo" className="fixed inset-0 z-50 flex items-end bg-black/80 p-4 sm:items-center"><div className="max-h-[85vh] w-full overflow-y-auto rounded-2xl bg-zinc-950 p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Change Photo</h2><button type="button" onClick={closePhoto} className="text-sm text-zinc-400">Cancel</button></div><p className="mb-3 text-xs text-zinc-400">Search API-Football, then explicitly choose a photo. Names and player data will not change.</p><div className="flex gap-2"><input aria-label="Search API player for photo" value={photoQuery} onChange={event => setPhotoQuery(event.target.value)} placeholder="Player name" className="min-w-0 flex-1 rounded-xl bg-zinc-900 px-3 py-2 text-sm" /><button type="button" onClick={() => void searchPhotos()} disabled={photoLoading} className="rounded-xl bg-zinc-800 px-3 py-2 text-xs font-bold disabled:opacity-40">{photoLoading ? 'Searching…' : 'Search'}</button></div>{photoError && <p role="alert" className="mt-2 text-xs text-amber-300">{photoError}</p>}<div className="mt-3 space-y-1">{photoResults.map(candidate => <button key={candidate.id} type="button" onClick={() => setPhotoSelected(candidate)} className={`flex w-full items-center gap-3 rounded-xl p-2 text-left ${photoSelected?.id === candidate.id ? 'bg-emerald-500/15 ring-1 ring-emerald-400' : 'bg-zinc-900'}`}><PlayerAvatar photoUrl={candidate.photo} number={candidate.number ?? undefined} className="h-10 w-10 text-[10px]" /><span className="min-w-0"><b className="block truncate text-sm">{candidate.name}</b><span className="block truncate text-[10px] text-zinc-400">{candidate.position || 'Outfield'} · {candidate.age ? `${candidate.age} yrs` : 'Age unavailable'}{candidate.nationality ? ` · ${candidate.nationality}` : ''}{candidate.currentTeam ? ` · ${candidate.currentTeam}` : ''}</span></span></button>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={removePhoto} className="rounded-xl bg-zinc-800 py-3 text-xs font-bold">Remove Photo</button><button type="button" disabled={!photoSelected?.photo} onClick={usePhoto} className="rounded-xl bg-emerald-500 py-3 text-xs font-black text-black disabled:opacity-40">Use This Photo</button></div></div></div>}
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{recordedTeamIds.map(teamId => { const team = teams.find(item => item.id === teamId); const included = selectedTeamIds.includes(teamId); return <button key={teamId} type="button" onClick={() => setSelectedTeamIds(ids => included ? ids.filter(id => id !== teamId) : [...ids, teamId])} className={`shrink-0 rounded-full px-3 py-1.5 text-[10px] font-black ${included ? 'bg-emerald-500/15 text-emerald-300' : 'bg-zinc-800 text-zinc-500'}`}>{included ? <TeamIcon team={team} className="h-4 w-12 text-[8px] uppercase">{team?.shortName}</TeamIcon> : team?.shortName}</button> })}</div>
    <section className="mb-4 rounded-2xl border border-white/5 bg-zinc-900 p-3"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Player form</h2><p className="text-[10px] text-zinc-500">Unused bench ratings are excluded</p></div><span className="max-w-40 truncate text-[10px] text-zinc-400">{form.ratings.slice(-5).map(item => item.rating.toFixed(1)).join(' · ') || '—'}</span></div><div className="grid grid-cols-3 gap-2">{[['Season Avg', form.seasonAverage], ['Last 5', form.last5Average], ['Last 3', form.last3Average]].map(([label, value], index) => <div key={String(label)} className="rounded-xl bg-black/20 px-2 py-2 text-center"><p className={`text-base font-black ${index > 0 && Number(value) > form.seasonAverage ? 'text-emerald-400' : ''}`}>{Number(value) ? `${Number(value).toFixed(2)}${index > 0 && Number(value) > form.seasonAverage ? ' ↑' : ''}` : '—'}</p><p className="text-[9px] uppercase text-zinc-500">{label}</p></div>)}</div></section>
    <section className="mb-4"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">Streaks</h2><span className="text-[10px] text-zinc-500">Current / best</span></div><div className="grid grid-cols-2 gap-1.5">{streaks.map(streak => <div key={streak.key} className="flex items-center justify-between rounded-xl bg-zinc-900 px-3 py-2 text-xs"><span className="text-zinc-400">{streak.label}</span><b>{streak.current}<span className="text-zinc-600"> / </span>{streak.best}</b></div>)}</div></section>
    <div className="mb-4 grid grid-cols-4 gap-2">{[['Avg', average ? average.toFixed(2) : '—'], ['Apps', rated.length], ['G', goals], ['A', assists]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-zinc-900 px-2 py-3 text-center"><div className="text-lg font-bold">{value}</div><div className="text-[10px] uppercase text-zinc-500">{label}</div></div>)}</div>
    <section className="mb-5"><h2 className="mb-2 text-sm font-semibold">Position splits</h2><div className="space-y-1.5">{positions.map(row => <div key={row.position} className="grid grid-cols-[34px_1fr_auto] items-center gap-2 rounded-xl bg-zinc-900 px-3 py-2 text-xs"><b>{row.position}</b><span className="text-zinc-400">{row.matches} apps · {row.minutes}' · G+A {row.combinedGA}</span><span className="font-black">{row.averageRating.toFixed(2)}</span></div>)}</div></section>
    <section className="mb-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">Starter / Substitute</h2><span className="text-xs font-black text-zinc-400">On-pitch {onPitch.plusMinus > 0 ? '+' : ''}{onPitch.plusMinus}</span></div><div className="grid grid-cols-2 gap-2">{([['As Starter', roles.starter], ['As Substitute', roles.substitute]] as const).map(([label, row]) => <div key={label} className="rounded-xl bg-zinc-900 p-3"><p className="mb-1 text-xs font-bold">{label}</p><p className="text-[11px] text-zinc-400">Apps {row.apps} · {row.minutes}'</p><p className="text-[11px] text-zinc-400">Rating {row.averageRating ? row.averageRating.toFixed(2) : '—'} · G+A {row.combinedGA}</p></div>)}</div></section>
    <h2 className="mb-2 text-sm font-semibold">Previous matches · {active}</h2><div className="space-y-3">{records.length === 0 && <p className="text-xs text-zinc-500">No match records this season for selected teams.</p>}{records.map(match => { const appearance = match.appearances.find(item => item.playerId === player.id)!; const rating = ratePlayerMatch(match, player); const matchGoals = match.events.filter(event => event.type === 'goal' && !event.ownGoal && event.playerId === player.id).length; const matchAssists = match.events.filter(event => event.type === 'goal' && !event.ownGoal && event.assistPlayerId === player.id).length; const score = matchScore(match); const home = teams.find(team => team.id === match.homeTeamId); const away = teams.find(team => team.id === match.awayTeamId); const isMom = getMatchManOfTheMatch(match, players) === player.id; return <button key={match.id} type="button" onClick={() => onNavigate({ name: 'match', id: match.id })} className="w-full rounded-2xl bg-zinc-900 p-3 text-left"><div className="mb-2 flex items-center justify-between"><span className="text-xs text-zinc-400">MD {match.matchDay} · {formatDate(match.date)} · {rating ? `${rating.minutes}' ${rating.starter ? 'XI' : 'Sub'}` : 'Bench'}</span><span className={`text-lg font-bold ${isMom ? 'text-blue-400' : rating ? ratingTone(rating.rating) : 'text-zinc-500'}`}>{rating ? rating.raw.toFixed(1) : '-'}</span></div><div className="mb-2 flex items-center justify-between text-sm font-semibold"><span>{home?.shortName} {score.home}-{score.away} {away?.shortName}</span><ResultPill match={match} teamId={appearance.teamId} /></div><div className="mb-2 text-xs font-semibold text-zinc-300" aria-label="Match positions">{rating ? recentMatchPositions(match, appearance) : 'Bench'}</div>{rating && <div className="flex items-center gap-1 text-zinc-300">{Array.from({ length: matchGoals }).map((_, index) => <GoalIcon key={`g${index}`} />)}{Array.from({ length: matchAssists }).map((_, index) => <AssistIcon key={`a${index}`} />)}</div>}</button> })}</div>
  </div>
}
