import { useMemo, useState } from 'react'
import { PlayerAvatar } from '../components/PlayerAvatar'
import { formatDate, playerFullName, ratingTone } from '../components/ui'
import { GOOD_RATING_THRESHOLD } from '../engine/constants'
import { playerChemistry } from '../engine/analytics'
import { substituteImpact } from '../engine/substituteImpact'
import { derivePlayerScope, playerCareerTimeline, playerPersonalRecords } from '../engine/playerDerived'
import { matchScore, ratePlayerMatch } from '../engine/rating'
import { seasonsFromMatches } from '../engine/stats'
import { recentMatches, recentMatchPositions } from './recentMatches'
import { useStore } from '../store'
import type { CompetitionType, View } from '../types'

const competitions: { value: CompetitionType | 'all'; label: string }[] = [{ value: 'all', label: 'All competitions' }, { value: 'league', label: 'League' }, { value: 'cup', label: 'Cup' }, { value: 'champions', label: 'Champions' }]
const pct = (value: number) => `${value.toFixed(0)}%`
const value = (number: number | null | undefined, digits = 2) => number === null || number === undefined || !Number.isFinite(number) ? '—' : number.toFixed(digits)

export function PlayerDetailScreen({ playerId, season, onNavigate, onBack }: { playerId: string; season: string; onNavigate: (view: View) => void; onBack: () => void }) {
  const { players, teams, matches } = useStore()
  const player = players.find(item => item.id === playerId)
  const seasons = useMemo(() => seasonsFromMatches(matches), [matches])
  const [selectedSeason, setSelectedSeason] = useState(seasons.includes(season) ? season : seasons[0] ?? season)
  const [competition, setCompetition] = useState<CompetitionType | 'all'>('all')
  const data = player ? derivePlayerScope(player, players, matches, { season: selectedSeason, competition }) : null
  const career = player ? playerCareerTimeline(player, players, matches) : []
  const records = player ? playerPersonalRecords(player, players, matches) : null
  const chemistry = player ? playerChemistry(player, players, matches, { season: selectedSeason }) : null
  if (!player || !data || !records) return <div className="p-6 text-sm text-zinc-400">Player not found.</div>
  const currentTeam = teams.find(team => team.id === player.teamId)
  const recent = data.appearances.slice(-5)
  const recentAverage = recent.length ? recent.reduce((total, row) => total + row.rating.raw, 0) / recent.length : 0
  const formChange = recent.length ? recentAverage - data.averageRating : 0
  const positions = [...data.positionMinutes.entries()].map(([position, minutes]) => ({ position, minutes, share: data.minutes ? minutes / data.minutes * 100 : 0 })).filter(row => row.share >= 10).sort((left, right) => right.share - left.share || right.minutes - left.minutes)
  const substitute = substituteImpact(player, data.appearances.map(row => row.match))
  const matchHistory = recentMatches(matches.filter(match => match.season === selectedSeason && (competition === 'all' || (match.competitionType ?? 'league') === competition) && match.appearances.some(appearance => appearance.playerId === player.id)))
  const metric = (label: string, content: string | number) => <div key={label} className="rounded-xl bg-black/20 px-2 py-2 text-center"><b className="block text-sm">{content}</b><small className="block text-[9px] uppercase text-zinc-500">{label}</small></div>
  return <div className="px-4 pb-8 pt-6">
    <button type="button" onClick={onBack} className="mb-3 text-xs font-semibold text-emerald-400">Back</button>
    <header className="mb-4 flex items-start gap-3"><PlayerAvatar photoUrl={player.photoUrl || player.image} number={player.number} className="h-14 w-14 text-sm" /><div className="min-w-0 flex-1"><p className="text-xs text-zinc-400">{currentTeam?.name ?? 'No Team'} · #{player.number} · {player.position}</p><h1 className="break-words text-2xl font-semibold">{playerFullName(player)}</h1><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={() => onNavigate({ name: 'edit-player', id: player.id })} className="rounded-full bg-zinc-800 px-3 py-1.5 text-xs font-bold">Edit player</button><button type="button" onClick={() => onNavigate({ name: 'comparison' })} className="rounded-full bg-zinc-800 px-3 py-1.5 text-xs font-bold">Compare</button></div></div></header>
    <div className="mb-4 grid grid-cols-2 gap-2"><label className="text-[10px] text-zinc-500">Season<select aria-label="Player detail season" value={selectedSeason} onChange={event => setSelectedSeason(event.target.value)} className="mt-1 w-full rounded-xl bg-zinc-900 px-3 py-2 text-xs text-white">{seasons.map(item => <option key={item}>{item}</option>)}</select></label><label className="text-[10px] text-zinc-500">Competition<select aria-label="Player detail competition" value={competition} onChange={event => setCompetition(event.target.value as CompetitionType | 'all')} className="mt-1 w-full rounded-xl bg-zinc-900 px-3 py-2 text-xs text-white">{competitions.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label></div>
    <section className="mb-4 rounded-2xl border border-white/5 bg-zinc-900 p-3"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">Overview</h2><b className={ratingTone(data.averageRating || 6)}>{data.apps ? value(data.averageRating) : '—'}</b></div><div className="grid grid-cols-4 gap-1.5">{metric('Apps', data.apps)}{metric('Starts', data.starts)}{metric('Sub Apps', data.subs)}{metric('Minutes', data.minutes)}{metric('Start rate', data.apps ? pct(data.starts / data.apps * 100) : '—')}{metric('Min/App', data.apps ? value(data.minutes / data.apps, 1) : '—')}{metric('Goals', data.goals)}{metric('Assists', data.assists)}{metric('G+A', data.goals + data.assists)}{metric('MOM', data.mom)}{metric('MOM rate', data.apps ? pct(data.mom / data.apps * 100) : '—')}{metric('Good match', data.apps ? pct(data.goodMatchRate) : '—')}{metric('On-pitch GD/90', data.apps ? value(data.onPitchGdPer90) : '—')}{metric('Goal involvement', data.goalInvolvement === null ? '—' : pct(data.goalInvolvement))}{metric('Goals/90', data.apps ? value((data.goals * 90) / data.minutes) : '—')}{metric('G+A/90', data.apps ? value(((data.goals + data.assists) * 90) / data.minutes) : '—')}</div>
      {player.position === 'GK' && <div className="mt-2 grid grid-cols-4 gap-1.5">{metric('Saves', data.saves)}{metric('Save %', data.saves + data.onPitchGoalsAgainst ? pct(data.saves / (data.saves + data.onPitchGoalsAgainst) * 100) : '—')}{metric('GA/90', value(data.onPitchGaPer90))}{metric('Clean sheets', data.cleanSheets)}</div>}</section>
    <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Recent Form</h2><div className="mt-2 flex gap-1.5">{recent.map(row => <span key={row.match.id} className={`grid h-9 flex-1 place-items-center rounded-lg text-xs font-black ${ratingTone(row.rating.rating)}`}>{row.rating.rating.toFixed(1)}</span>)}{!recent.length && <span className="text-xs text-zinc-500">No actual appearances in this scope.</span>}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><span><b>{value(recentAverage)}</b><small className="block text-zinc-500">Last 5</small></span><span><b>{value(data.averageRating)}</b><small className="block text-zinc-500">Scope avg</small></span><span><b className={formChange > 0 ? 'text-emerald-400' : formChange < 0 ? 'text-red-400' : ''}>{formChange > 0 ? '+' : ''}{value(formChange)}</b><small className="block text-zinc-500">Change</small></span></div></section>
    <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Positions Played <span className="text-zinc-500">(Position splits)</span></h2>{positions.length ? <div className="mt-2 space-y-2">{positions.map(row => <div key={row.position} className="grid grid-cols-[32px_1fr_auto] items-center gap-2 text-xs"><b>{row.position}</b><span className="h-2 overflow-hidden rounded-full bg-black/30"><span className="block h-full bg-emerald-400" style={{ width: `${row.share}%` }} /></span><span>{pct(row.share)} · {row.minutes}'</span></div>)}</div> : <p className="mt-2 text-xs text-zinc-500">No position minutes yet.</p>}</section>
    {data.goals > 0 && <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Goal Types</h2><div className="mt-2 grid grid-cols-2 gap-1.5 text-xs">{([['opening', 'Opening'], ['equalizer', 'Equalizers'], ['goAhead', 'Go-ahead'], ['comeback', 'Comeback'], ['winning', 'Winning'], ['lateDrama', 'Late drama']] as const).filter(([key]) => data.goalTypes[key]).map(([key, label]) => <div key={key} className="flex justify-between rounded-lg bg-black/20 px-2 py-1.5"><span>{label}</span><b>{data.goalTypes[key]}</b></div>)}</div></section>}
    <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Starter / Substitute</h2><div className="mt-2 grid grid-cols-2 gap-2 text-xs">{([['Starter', data.starter], ['Substitute', data.substitute]] as const).map(([label, row]) => <div key={label} className="rounded-xl bg-black/20 p-2"><b>{label}</b><p className="mt-1 text-zinc-400">{row.apps} apps · {value(row.averageRating)}</p><p className="text-zinc-400">G+A/90 {value(row.gaPer90)} · G/90 {value(row.goalsPer90)} · A/90 {value(row.assistsPer90)}</p></div>)}</div></section>
    {data.startingPerformance.length > 0 && <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Team Performance When Starting</h2><p className="mt-1 text-[10px] text-zinc-500">Match-level team outcomes, not individual causation.</p><div className="mt-2 space-y-2">{data.startingPerformance.map(row => <div key={row.teamId} className="rounded-xl bg-black/20 p-2 text-xs"><b>{teams.find(team => team.id === row.teamId)?.name ?? row.teamId}</b><p className="mt-1 text-zinc-400">{row.starts} starts · {row.wins}-{row.draws}-{row.losses}</p><p>PPG {value(row.starterPpg)} vs team {value(row.teamPpg)} <b className={row.ppgDifference >= 0 ? 'text-emerald-400' : 'text-red-400'}>({row.ppgDifference >= 0 ? '+' : ''}{value(row.ppgDifference)})</b></p><p>GD/match {value(row.starterGdPerMatch)} vs team {value(row.teamGdPerMatch)} <b className={row.gdDifference >= 0 ? 'text-emerald-400' : 'text-red-400'}>({row.gdDifference >= 0 ? '+' : ''}{value(row.gdDifference)})</b></p></div>)}</div></section>}
    {chemistry && (chemistry.direct || chemistry.positional || chemistry.results) && <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Player Chemistry</h2><p className="mt-1 text-[10px] text-zinc-500">Evidence-based partnerships in {selectedSeason}.</p><div className="mt-2 space-y-2 text-xs">{chemistry.direct && <div className="rounded-xl bg-black/20 p-2"><b>Top goal connection · {playerFullName(players.find(item => item.id === chemistry.direct!.partnerId))}</b><p className="text-zinc-400">{chemistry.direct.connections} connections · player scored {chemistry.direct.playerScored} · partner scored {chemistry.direct.partnerScored}</p><p className="text-zinc-400">{chemistry.direct.matchesTogether} matches · {chemistry.direct.minutesTogether}' together</p></div>}{chemistry.positional && <div className="rounded-xl bg-black/20 p-2"><b>Best positional partner · {chemistry.positional.playerIds.filter(id => id !== player.id).map(id => playerFullName(players.find(item => item.id === id))).join(', ')}</b><p className="text-zinc-400">{chemistry.positional.startsTogether} starts · {chemistry.positional.matches} matches · {chemistry.positional.togetherMinutes}' together</p></div>}{chemistry.results && <div className="rounded-xl bg-black/20 p-2"><b>Best results together · {chemistry.results.playerIds.filter(id => id !== player.id).map(id => playerFullName(players.find(item => item.id === id))).join(', ')}</b><p className="text-zinc-400">PPG {value((chemistry.results.wins * 3 + chemistry.results.draws) / Math.max(chemistry.results.startsTogether, 1))} · GD {chemistry.results.goalDifference > 0 ? '+' : ''}{chemistry.results.goalDifference}</p></div>}</div></section>}
    <section className="mb-4 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Personal Records</h2><div className="mt-2 grid grid-cols-2 gap-1.5 text-xs">{metric('Highest rating', value(records.highestRating))}{metric('Goals in match', records.mostGoals)}{metric('Assists in match', records.mostAssists)}{metric('G+A in match', records.mostGA)}{metric('Scoring streak', records.scoringStreak)}{metric('G+A streak', records.contributionStreak)}{metric(`${GOOD_RATING_THRESHOLD}+ streak`, records.goodMatchStreak)}</div></section>
    <section className="mb-5"><h2 className="mb-2 text-sm font-semibold">Career Timeline</h2><div className="space-y-1.5">{career.map(row => <div key={`${row.season}:${row.teamId}`} className="rounded-xl bg-zinc-900 px-3 py-2 text-xs"><b>{row.season} · {teams.find(team => team.id === row.teamId)?.shortName ?? row.teamId}</b><p className="text-zinc-400">{row.apps} apps · {row.goals}G · {row.assists}A · {value(row.averageRating)}</p></div>)}</div></section>
    <section><h2 className="mb-2 text-sm font-semibold">Matches</h2><div className="space-y-2">{data.appearances.slice().reverse().map(row => { const score = matchScore(row.match); return <article key={row.match.id} className="rounded-2xl bg-zinc-900 p-3"><button type="button" onClick={() => onNavigate({ name: 'match', id: row.match.id })} className="flex w-full justify-between text-left"><span className="text-xs">MD {row.match.matchDay} · {formatDate(row.match.date)} · {score.home}-{score.away}</span><b className={ratingTone(row.rating.rating)}>{row.rating.rating.toFixed(1)}</b></button><details className="mt-2 border-t border-white/5 pt-2 text-xs"><summary className="cursor-pointer text-zinc-400">Rating Details · {row.rating.position} · {row.rating.minutes}'</summary><div className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-zinc-300"><span>Base</span><b>{value(row.rating.base)}</b><span>SOT suppression</span><b>+{value(row.rating.noConceded)}</b><span>Goals conceded</span><b>{value(row.rating.conceded)}</b><span>Goal / assist</span><b>+{value(row.rating.goals + row.rating.assists)}</b><span>Team goals</span><b>+{value(row.rating.teamGoals)}</b><span>Result</span><b>{value(row.rating.result)}</b><span>Cause / saves</span><b>{value(row.rating.concededCause + row.rating.saves)}</b><span>Raw rating</span><b>{value(row.rating.raw)}</b></div></details></article>})}{!data.appearances.length && <p className="text-xs text-zinc-500">No actual appearances in this scope.</p>}</div></section>
    {substitute.summary.apps > 0 && <section className="mt-5 rounded-2xl bg-zinc-900 p-3"><h2 className="text-sm font-semibold">Substitute Impact</h2><p className="mt-1 text-[10px] text-zinc-500">Team performance during the player's substitute on-pitch period.</p><div className="mt-2 grid grid-cols-4 gap-1.5 text-xs">{metric('Sub apps', substitute.summary.apps)}{metric('Minutes', substitute.summary.minutes)}{metric('Goals', substitute.summary.goals)}{metric('Assists', substitute.summary.assists)}{metric('G+A/90', value(substitute.summary.gaPer90))}{metric('On-pitch GF', substitute.summary.goalsFor)}{metric('On-pitch GA', substitute.summary.goalsAgainst)}{metric('On-pitch GD', `${substitute.summary.goalDifference > 0 ? '+' : ''}${substitute.summary.goalDifference}`)}{metric('GD/90', value(substitute.summary.gdPer90))}{metric('Avg rating', value(substitute.summary.averageRating))}</div><div className="mt-3 space-y-2">{substitute.appearances.map(row => <div key={row.match.id} className="rounded-xl bg-black/20 p-2 text-xs"><div className="flex justify-between"><b>Entered {row.entryMinute}' · {row.result}</b><b className={ratingTone(row.rating.rating)}>{row.rating.rating.toFixed(1)}</b></div><p className="text-zinc-400">At entry {row.scoreAtEntry.home}-{row.scoreAtEntry.away} · Final {row.finalScore.home}-{row.finalScore.away}</p><p className="text-zinc-400">After entry: GF {row.goalsFor} · GA {row.goalsAgainst} · GD {row.goalDifference > 0 ? '+' : ''}{row.goalDifference} · {row.goals}G {row.assists}A</p></div>)}</div></section>}
    <section className="mt-5"><h2 className="mb-2 text-sm font-semibold">Previous matches</h2><div className="space-y-2">{matchHistory.map(match => { const appearance = match.appearances.find(item => item.playerId === player.id)!; const rating = ratePlayerMatch(match, player); return <button key={match.id} type="button" onClick={() => onNavigate({ name: 'match', id: match.id })} className="w-full rounded-xl bg-zinc-900 p-3 text-left"><div className="flex justify-between"><span className="text-xs">MD {match.matchDay} · {formatDate(match.date)} · {rating ? `${rating.minutes}'` : 'Bench'}</span><span className={`text-lg font-bold ${rating ? ratingTone(rating.rating) : 'text-zinc-500'}`}>{rating ? rating.rating.toFixed(1) : '-'}</span></div><span aria-label="Match positions" className="mt-1 block text-xs text-zinc-400">{rating ? recentMatchPositions(match, appearance) : 'Bench'}</span></button>})}</div></section>
  </div>
}
