import { useMemo, useState } from 'react'
import { CombinationRecords } from '../components/CombinationRecords'
import { competitionHistory } from '../engine/competition'
import { getMatchManOfTheMatch, matchScore } from '../engine/rating'
import { playerForm } from '../engine/seasonInsights'
import { aggregatePlayerStats, buildGlobalRankingData, seasonsFromMatches, unifiedBestEleven } from '../engine/stats'
import { currentStaticTeams } from '../data/teams'
import { playerFullName } from '../components/ui'
import { useStore } from '../store'
import { emptyFilters, matchesForPlayer, RankingFilterButton, type RankingFilters } from './RankingFilters'
import { awardsForCompetition, seasonAwards } from '../engine/awards'
import { auditDataIntegrity } from '../engine/integrity'
import type { Match, Player, Team, View } from '../types'

type Category = 'player' | 'combination' | 'team' | 'history' | 'insights' | 'integrity'
type Row = { id: string; name: string; value: string; numeric: number; detail: string }
type Group = { id: string; title: string; rows: (Row & { rank: number })[] }
const tabs: [Category, string, string][] = [['player', 'Player', '⚽'], ['combination', 'Combination', '🤝'], ['team', 'Team', '🛡️'], ['history', 'History', '🏆'], ['insights', 'Insights', '📈'], ['integrity', 'Data Integrity', '✓']]
const rank = (rows: Row[]) => { let prior: number | undefined; let priorRank = 0; return rows.slice().sort((a, b) => b.numeric - a.numeric || a.name.localeCompare(b.name)).map((row, index) => { const next = prior === row.numeric ? priorRank : index + 1; prior = row.numeric; priorRank = next; return { ...row, rank: next } }) }
const scopedMatches = (matches: Match[], filters: RankingFilters) => matches.filter(match => (!filters.seasons.length || filters.seasons.includes(match.season)) && (!filters.teams.length || filters.teams.includes(match.homeTeamId) || filters.teams.includes(match.awayTeamId)))
function teamMetrics(team: Team, matches: Match[]) { const games = matches.filter(match => match.homeTeamId === team.id || match.awayTeamId === team.id).sort((a, b) => a.date.localeCompare(b.date) || a.matchDay - b.matchDay); let wins = 0; let goals = 0; let conceded = 0; let cleanSheets = 0; let opponentSot = 0; const form = games.map(match => { const score = matchScore(match); const ours = match.homeTeamId === team.id ? score.home : score.away; const theirs = match.homeTeamId === team.id ? score.away : score.home; wins += Number(ours > theirs); goals += ours; conceded += theirs; cleanSheets += Number(theirs === 0); opponentSot += theirs + match.events.reduce((sum, event) => sum + (event.type === 'save' && event.teamId === team.id ? event.count ?? 1 : 0), 0); return ours > theirs ? 'W' : ours === theirs ? 'D' : 'L' }); return { games, wins, goals, conceded, cleanSheets, opponentSot, form: form.slice(-5).reverse() } }

export function RecordsScreen({ season, onNavigate }: { season: string; onNavigate: (view: View) => void }) {
  const { players, teams, matches, competitionStates = [] } = useStore()
  const [category, setCategory] = useState<Category>('player')
  const [filters, setFilters] = useState<RankingFilters>(emptyFilters)
  const filtersApply = category === 'player' || category === 'team' || category === 'combination'
  return <div className="px-4 pb-8 pt-6"><div className="mb-4 flex items-center justify-between"><div><h1 className="text-2xl font-semibold">Records</h1><p className="text-[10px] text-zinc-500">Leaders, partnerships and football history</p></div>{filtersApply && <RankingFilterButton applied={filters} onApply={setFilters} seasons={seasonsFromMatches(matches)} teams={teams} />}</div><div className="no-scrollbar mb-5 flex gap-1 overflow-x-auto rounded-xl bg-zinc-900 p-1">{tabs.map(([id, label, icon]) => <button key={id} type="button" onClick={() => setCategory(id)} className={`shrink-0 rounded-lg px-3 py-2 text-[10px] font-bold ${category === id ? 'bg-emerald-500 text-black' : 'text-zinc-400'}`}><span aria-hidden="true">{icon}</span> {label}</button>)}</div>
    {category === 'player' && <PlayerRecords players={players} matches={matches} filters={filters} onNavigate={onNavigate} />}
    {category === 'combination' && <CombinationScope players={players} matches={matches} filters={filters} />}
    {category === 'team' && <TeamRecords teams={teams} matches={matches} filters={filters} />}
    {category === 'history' && <HistoryRecords players={players} teams={teams} matches={matches} states={competitionStates} />}
    {category === 'insights' && <InsightsRecords season={season} players={players} teams={teams} matches={matches} onNavigate={onNavigate} />}
    {category === 'integrity' && <IntegrityRecords players={players} teams={teams} matches={matches} onNavigate={onNavigate} />}
  </div>
}

function PlayerRecords({ players, matches, filters, onNavigate }: { players: Player[]; matches: Match[]; filters: RankingFilters; onNavigate: (view: View) => void }) {
  const scoped = useMemo(() => scopedMatches(matches, filters), [matches, filters])
  const rows = useMemo(() => players.map(player => { const games = matchesForPlayer(player, scoped, filters); return { player, games, stats: aggregatePlayerStats(player, players, games) } }), [players, scoped, filters])
  const groups = useMemo<Group[]>(() => { const group = (id: string, title: string, metric: (row: typeof rows[number]) => number, suffix: string, detail: (row: typeof rows[number]) => string): Group => ({ id, title, rows: rank(rows.map(row => ({ id: row.player.id, name: playerFullName(row.player), numeric: metric(row), value: `${metric(row)}${suffix}`, detail: detail(row) }))) }); return [group('goals', 'All-time Goals', row => row.stats.goals, ' goals', row => `${row.stats.assists} assists · ${row.stats.matches} apps`), group('assists', 'All-time Assists', row => row.stats.assists, ' assists', row => `${row.stats.goals} goals · ${row.stats.matches} apps`), group('ga', 'All-time G+A', row => row.stats.goals + row.stats.assists, ' G+A', row => `${row.stats.matches} apps`), group('mom', 'Most MOM', row => row.games.filter(match => getMatchManOfTheMatch(match, players) === row.player.id).length, ' MOM', row => `${row.stats.matches} apps`), group('apps', 'Most Appearances', row => row.stats.matches, ' apps', row => `${row.stats.minutes}'`), group('saves', 'Most Career Saves', row => row.stats.saves, ' saves', row => `${row.stats.matches} apps`)] }, [rows, players])
  return <Leaderboard groups={groups} onOpen={id => onNavigate({ name: 'player', id })} />
}
function TeamRecords({ teams, matches, filters }: { teams: Team[]; matches: Match[]; filters: RankingFilters }) { const scoped = useMemo(() => scopedMatches(matches, filters), [matches, filters]); const groups = useMemo<Group[]>(() => { const stats = teams.map(team => ({ team, stats: teamMetrics(team, scoped) })); const group = (id: string, title: string, metric: (row: typeof stats[number]) => number, suffix: string): Group => ({ id, title, rows: rank(stats.map(row => ({ id: row.team.id, name: row.team.name, numeric: metric(row), value: `${metric(row)}${suffix}`, detail: `${row.stats.games.length} matches · ${row.stats.goals} GF / ${row.stats.conceded} GA` }))) }); return [group('wins', 'Most Wins', row => row.stats.wins, ' wins'), group('team-goals', 'Most Goals', row => row.stats.goals, ' goals'), group('clean', 'Most Clean Sheets', row => row.stats.cleanSheets, ' CS')] }, [teams, scoped]); return <Leaderboard groups={groups} /> }
function CombinationScope({ players, matches, filters }: { players: Player[]; matches: Match[]; filters: RankingFilters }) { const scoped = useMemo(() => scopedMatches(matches, filters), [matches, filters]); return <CombinationRecords players={players} matches={scoped} /> }

function Leaderboard({ groups, onOpen }: { groups: Group[]; onOpen?: (id: string) => void }) { const [expanded, setExpanded] = useState<string | null>(null); return <div>{groups.map(group => { const rows = expanded === group.id ? group.rows.slice(0, 50) : group.rows.slice(0, 3); const leader = rows[0]; return <section key={group.id} className="mb-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">{group.title}</h2>{group.rows.length > 3 && <button type="button" onClick={() => setExpanded(expanded === group.id ? null : group.id)} className="secondary-view-all">{expanded === group.id ? 'Show Less' : 'View All'}</button>}</div>{leader && <button type="button" onClick={() => onOpen?.(leader.id)} className="mb-2 grid w-full grid-cols-[auto_1fr_auto] items-center gap-3 rounded-2xl border border-amber-300/20 bg-gradient-to-r from-amber-300/15 to-zinc-900 p-3 text-left"><span className="text-xl">🥇</span><span className="min-w-0"><b className="block truncate">{leader.name}</b><small className="block truncate text-zinc-400">{leader.detail}</small></span><b className="text-amber-200">{leader.value}</b></button>}<div className="overflow-hidden rounded-xl bg-zinc-900">{rows.slice(1).map(row => <button key={row.id} type="button" onClick={() => onOpen?.(row.id)} className="grid w-full grid-cols-[24px_1fr_auto] gap-2 border-b border-white/5 px-3 py-2.5 text-left text-xs last:border-0"><b className="text-zinc-500">#{row.rank}</b><span className="min-w-0"><b className="block truncate">{row.name}</b><small className="block truncate text-zinc-500">{row.detail}</small></span><b className="text-emerald-400">{row.value}</b></button>)}</div></section> })}</div> }

function HistoryRecords({ players, teams, matches, states }: { players: Player[]; teams: Team[]; matches: Match[]; states: Parameters<typeof competitionHistory>[3] }) {
  const tournamentTeams = useMemo(() => currentStaticTeams(teams), [teams])
  const champions = useMemo(() => competitionHistory(tournamentTeams, matches, players, states), [tournamentTeams, matches, players, states])
  const history = useMemo(() => champions.map(entry => { const games = matches.filter(match => match.season === entry.season); const stats = buildGlobalRankingData(players, games, { seasons: [entry.season], teams: [], positions: [] }, 'rating'); const scorer = stats.slice().sort((a, b) => b.goals - a.goals)[0]; const assists = stats.slice().sort((a, b) => b.assists - a.assists)[0]; const rating = stats[0]; const mom = stats.slice().sort((a, b) => b.mom - a.mom)[0]; const xi = unifiedBestEleven(players, games, entry.season).slots.flatMap(slot => slot.playerId ? [playerFullName(players.find(player => player.id === slot.playerId))] : []); return { ...entry, scorer, assists, rating, mom, xi, awards: { league: awardsForCompetition('league', entry.season, tournamentTeams, players, matches, states), cup: awardsForCompetition('cup', entry.season, tournamentTeams, players, matches, states), champions: awardsForCompetition('champions', entry.season, tournamentTeams, players, matches, states), season: seasonAwards(entry.season, tournamentTeams, players, matches, states) } } }), [champions, matches, players, tournamentTeams, states])
  const trophies = useMemo(() => teams.map(team => { const league = champions.filter(row => row.league === team.id).length; const cup = champions.filter(row => row.cup === team.id).length; const championsTitles = champions.filter(row => row.champions === team.id).length; return { team, league, cup, champions: championsTitles, total: league + cup + championsTitles } }).filter(row => row.total).sort((a, b) => b.total - a.total), [teams, champions])
  const name = (id?: string) => id ? teams.find(team => team.id === id)?.name ?? '—' : '—'; const playerName = (id?: string) => id ? playerFullName(players.find(player => player.id === id)) : '—'
  return <><section className="mb-6"><h2 className="mb-2 text-sm font-semibold">Season History</h2><div className="space-y-3">{history.slice().reverse().map(row => <details key={row.season} className="rounded-2xl bg-zinc-900 p-3"><summary className="cursor-pointer text-sm font-black">🏆 {row.season} Awards</summary><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><Award label="👑 League Champion" value={name(row.league)} /><Award label="🥇 Cup Champion" value={name(row.cup)} /><Award label="🏆 Champions Champion" value={name(row.champions)} /><Award label="⚽ Golden Boot" value={`${playerName(row.scorer?.playerId)} · ${row.scorer?.goals ?? 0}`} /><Award label="🅰️ Assist Leader" value={`${playerName(row.assists?.playerId)} · ${row.assists?.assists ?? 0}`} /><Award label="🌟 Best Avg Rating" value={`${playerName(row.rating?.playerId)} · ${row.rating?.avgRating.toFixed(2) ?? '—'}`} /><Award label="MOM" value={`${playerName(row.mom?.playerId)} · ${row.mom?.mom ?? 0}`} /></div>{row.xi.length > 0 && <p className="mt-3 text-[10px] leading-relaxed text-zinc-400"><b className="text-zinc-200">Team of the Season:</b> {row.xi.join(', ')}</p>}</details>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">Trophy Cabinet</h2><div className="overflow-hidden rounded-xl bg-zinc-900">{trophies.map(row => <div key={row.team.id} className="grid grid-cols-[1fr_repeat(4,32px)] border-b border-white/5 px-3 py-2.5 text-[10px] last:border-0"><b className="truncate">{row.team.name}</b><span>👑{row.league}</span><span>🥇{row.cup}</span><span>🏆{row.champions}</span><b className="text-emerald-300">{row.total}</b></div>)}</div></section></>
}
function InsightsRecords({ season, players, teams, matches, onNavigate }: { season: string; players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) { const insights = useMemo(() => { const games = matches.filter(match => match.season === season); const teamRows = teams.map(team => ({ team, ...teamMetrics(team, games) })).filter(row => row.games.length).sort((a, b) => b.form.filter(result => result === 'W').length - a.form.filter(result => result === 'W').length).slice(0, 5); const playerRows = players.map(player => ({ player, form: playerForm(player, games) })).filter(row => row.form.ratings.length >= 3).sort((a, b) => b.form.last5Average - a.form.last5Average).slice(0, 5); return { teams: teamRows, players: playerRows } }, [teams, players, matches, season]); return <><section className="mb-6"><h2 className="mb-2 text-sm font-semibold">Team Form · {season}</h2><div className="grid gap-2">{insights.teams.map(row => <div key={row.team.id} className="rounded-xl bg-zinc-900 p-3"><div className="flex justify-between text-xs"><b>{row.team.name}</b><span className="tracking-widest">{row.form.join(' ')}</span></div><div className="mt-2 grid grid-cols-3 gap-1 text-center text-[10px]"><span>{(row.goals / row.games.length).toFixed(2)}<small className="block text-zinc-500">GF/M</small></span><span>{(row.conceded / row.games.length).toFixed(2)}<small className="block text-zinc-500">GA/M</small></span><span>{(row.opponentSot / row.games.length).toFixed(2)}<small className="block text-zinc-500">SOT/M</small></span></div></div>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">In-form Players</h2><div className="space-y-2">{insights.players.map(row => <button key={row.player.id} type="button" onClick={() => onNavigate({ name: 'player', id: row.player.id })} className="flex w-full justify-between rounded-xl bg-zinc-900 p-3 text-left text-xs"><b>{playerFullName(row.player)}</b><span className="text-emerald-300">Last 5 · {row.form.last5Average.toFixed(2)}</span></button>)}</div></section></> }
function IntegrityRecords({ players, teams, matches, onNavigate }: { players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) { const integrity = useMemo(() => auditDataIntegrity(matches, players, teams), [matches, players, teams]); return <section><div className="rounded-2xl bg-zinc-900 p-4"><h2 className="text-sm font-semibold">Data Integrity</h2><p className="mt-1 text-[10px] text-zinc-500">Read-only diagnostics. No football data is changed.</p><p className="mt-3 text-xs">{integrity.issues.length ? `${integrity.errors} errors · ${integrity.warnings} warnings` : '✓ No issues found.'}</p></div>{integrity.issues.length > 0 && <div className="mt-3 space-y-2">{integrity.issues.map((issue, index) => <div key={`${issue.matchId ?? 'global'}-${index}`} className="rounded-xl bg-zinc-900 p-3 text-xs"><div className="flex items-center justify-between gap-3"><b className={issue.severity === 'error' ? 'text-rose-300' : issue.severity === 'warning' ? 'text-amber-300' : 'text-sky-300'}>{issue.severity.toUpperCase()}</b>{issue.matchId && <button type="button" onClick={() => onNavigate({ name: 'match', id: issue.matchId! })} className="text-[10px] text-emerald-300">Open match</button>}</div><p className="mt-1 text-zinc-300">{issue.message}</p></div>)}</div>}</section> }
function Award({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-black/30 p-2"><small className="block text-zinc-500">{label}</small><b className="mt-1 block break-words">{value}</b></div> }
