import { useMemo, useState } from 'react'
import { competitionHistory } from '../engine/competition'
import { matchScore } from '../engine/rating'
import { playerForm } from '../engine/seasonInsights'
import { buildGlobalRankingData, seasonsFromMatches, unifiedBestEleven } from '../engine/stats'
import { combinationStats } from '../engine/analytics'
import { currentStaticTeams } from '../data/teams'
import { playerDisplayName, playerFullName } from '../components/ui'
import { formatSignedTwoDecimals } from '../lib/signedNumber'
import { useStore } from '../store'
import { emptyFilters, RankingFilterButton, type RankingFilters } from './RankingFilters'
import { awardsForCompetition, seasonAwards } from '../engine/awards'
import { buildSeasonAnalytics } from '../engine/seasonAnalytics'
import { auditDataIntegrity } from '../engine/integrity'
import { newestMatches, oldestMatches } from '../engine/matchChronology'
import { matchCompetitionType } from '../engine/competition'
import { CompetitionScopeSelector } from '../components/CompetitionScopeSelector'
import { FloatingScrollToTop } from '../components/FloatingScrollToTop'
import { buildPlayerRecordLeaderboards } from '../engine/playerRecords'
import { RecordsHistory } from './RecordsHistory'
import { PositionFilter } from '../components/PositionFilter'
import type { CompetitionType, Match, Player, RecordsCategory, ScreenStateByView, Team, View } from '../types'

type Category = RecordsCategory
type Row = { id: string; name: string; value: string; numeric: number; detail: string }
type Group = { id: string; title: string; rows: (Row & { rank: number })[] }
const tabs: [Category, string, string][] = [['player', 'Player', '⚽'], ['combination', 'Combination', '🤝'], ['team', 'Team', '🛡️'], ['history', 'History', '🏆'], ['insights', 'Insights', '📈'], ['integrity', 'Data Integrity', '✓']]
const rank = (rows: Row[]) => { let prior: number | undefined; let priorRank = 0; return rows.slice().sort((a, b) => b.numeric - a.numeric || a.name.localeCompare(b.name)).map((row, index) => { const next = prior === row.numeric ? priorRank : index + 1; prior = row.numeric; priorRank = next; return { ...row, rank: next } }) }
const combinationKey = (ids: string[]) => ids.slice().sort().join(':')
const scopedMatches = (matches: Match[], filters: RankingFilters, competition: CompetitionType | 'all' = 'all') => matches.filter(match => (!filters.seasons.length || filters.seasons.includes(match.season)) && (!filters.teams.length || filters.teams.includes(match.homeTeamId) || filters.teams.includes(match.awayTeamId)) && (competition === 'all' || matchCompetitionType(match) === competition))
function teamMetrics(team: Team, matches: Match[]) { const games = newestMatches(matches.filter(match => match.homeTeamId === team.id || match.awayTeamId === team.id)); let wins = 0; let goals = 0; let conceded = 0; let cleanSheets = 0; let opponentSot = 0; const form = games.map(match => { const score = matchScore(match); const ours = match.homeTeamId === team.id ? score.home : score.away; const theirs = match.homeTeamId === team.id ? score.away : score.home; wins += Number(ours > theirs); goals += ours; conceded += theirs; cleanSheets += Number(theirs === 0); opponentSot += theirs + match.events.reduce((sum, event) => sum + (event.type === 'save' && event.teamId === team.id ? event.count ?? 1 : 0), 0); return ours > theirs ? 'W' : ours === theirs ? 'D' : 'L' }); return { games, wins, goals, conceded, cleanSheets, opponentSot, form: form.slice(0, 5) } }

export function RecordsScreen({ season, screenState, onStateChange, onNavigate }: { season: string; screenState: ScreenStateByView['records']; onStateChange: (state: ScreenStateByView['records']) => void; onNavigate: (view: View) => void }) {
  const { players, teams, matches, competitionStates = [] } = useStore()
  const { category, competition } = screenState
  const patchState = (patch: Partial<ScreenStateByView['records']>) => onStateChange({ ...screenState, ...patch })
  const setCategory = (value: Category) => patchState({ category: value, expandedLeaderboardId: null })
  const setCompetition = (value: CompetitionType | 'all') => patchState({ competition: value, expandedLeaderboardId: null })
  const filters: RankingFilters = { ...emptyFilters, seasons: screenState.filterSeasonIds, teams: screenState.filterTeamIds }
  const setFilters = (value: RankingFilters) => patchState({ filterSeasonIds: value.seasons, filterTeamIds: value.teams, expandedLeaderboardId: null })
  const filtersApply = category !== 'history' && category !== 'integrity'
  return <div className="px-4 pb-8 pt-6"><div className="mb-4 flex items-center justify-between gap-2"><div><h1 className="text-2xl font-semibold">Records</h1><p className="text-[10px] text-zinc-500">Leaders, partnerships and football history</p></div><div className="flex shrink-0 items-center gap-1.5">{category === 'player' && <PositionFilter value={screenState.positionFilter} onChange={positionFilter => patchState({ positionFilter, expandedLeaderboardId: null })} label="Player Records position" />}{filtersApply && <RankingFilterButton applied={filters} onApply={setFilters} seasons={seasonsFromMatches(matches)} teams={teams} />}</div></div><div className="sticky top-0 z-20 -mx-4 mb-3 border-y border-white/5 bg-black/95 px-4 py-2"><CompetitionScopeSelector value={competition} onChange={setCompetition} /></div><div className="no-scrollbar mb-5 mt-3 flex gap-1 overflow-x-auto rounded-xl bg-zinc-900 p-1">{tabs.map(([id, label, icon]) => <button key={id} type="button" onClick={() => setCategory(id)} className={`shrink-0 rounded-lg px-3 py-2 text-[10px] font-bold ${category === id ? 'bg-emerald-500 text-black' : 'text-zinc-400'}`}><span aria-hidden="true">{icon}</span> {label}</button>)}</div>
    {category === 'player' && <PlayerRecords players={players} matches={matches} filters={filters} competition={competition} positionFilter={screenState.positionFilter} expandedLeaderboardId={screenState.expandedLeaderboardId} onExpandedLeaderboard={value => patchState({ expandedLeaderboardId: value })} onNavigate={onNavigate} />}
    {category === 'combination' && <CombinationScope players={players} matches={matches} filters={filters} competition={competition} />}
    {category === 'team' && <ExpandedTeamRecords teams={teams} matches={matches} filters={filters} competition={competition} />}
    {category === 'history' && <RecordsHistory players={players} teams={teams} matches={matches} states={competitionStates} competition={competition} panel={screenState.historyPanel === 'awards' ? 'awards' : 'timeline'} openSeason={screenState.historySeason} openBlock={screenState.historyBlock} onPanel={panel => patchState({ historyPanel: panel, historyBlock: null })} onSeason={value => patchState({ historySeason: value, historyBlock: null })} onBlock={value => patchState({ historyBlock: value })} onPlayerOpen={id => onNavigate({ name: 'player', id })} />}
    {category === 'insights' && <InsightsRecords season={season} players={players} teams={teams} matches={scopedMatches(matches, filters, competition)} onNavigate={onNavigate} />}
    {category === 'integrity' && <IntegrityRecords players={players} teams={teams} matches={matches} onNavigate={onNavigate} />}
  </div>
}

function PlayerRecords({ players, matches, filters, competition, positionFilter, expandedLeaderboardId, onExpandedLeaderboard, onNavigate }: { players: Player[]; matches: Match[]; filters: RankingFilters; competition: CompetitionType | 'all'; positionFilter: ScreenStateByView['records']['positionFilter']; expandedLeaderboardId: string | null; onExpandedLeaderboard: (id: string | null) => void; onNavigate: (view: View) => void }) {
  const groups = useMemo<Group[]>(() => {
    const playerById = new Map(players.map(player => [player.id, player]))
    return buildPlayerRecordLeaderboards(players, matches, { seasons: filters.seasons, teamIds: filters.teams, competition, positionFilter }).map(group => ({
      ...group,
      rows: group.rows.map(row => ({ id: row.playerId, name: playerFullName(playerById.get(row.playerId)), numeric: row.numeric, value: row.value, detail: row.detail, rank: row.rank })),
    }))
  }, [players, matches, filters.seasons, filters.teams, competition, positionFilter])
  return <Leaderboard groups={groups} expanded={expandedLeaderboardId} onExpanded={onExpandedLeaderboard} onOpen={id => onNavigate({ name: 'player', id })} />
}

export function TeamRecords({ teams, matches, filters, competition }: { teams: Team[]; matches: Match[]; filters: RankingFilters; competition: CompetitionType | 'all' }) { const scoped = useMemo(() => scopedMatches(matches, filters, competition), [matches, filters, competition]); const groups = useMemo<Group[]>(() => { const stats = teams.map(team => ({ team, stats: teamMetrics(team, scoped) })); const group = (id: string, title: string, metric: (row: typeof stats[number]) => number, suffix: string): Group => ({ id, title, rows: rank(stats.map(row => ({ id: row.team.id, name: row.team.name, numeric: metric(row), value: `${metric(row)}${suffix}`, detail: `${row.stats.games.length} matches · ${row.stats.goals} GF / ${row.stats.conceded} GA` }))) }); return [group('wins', 'Most Wins', row => row.stats.wins, ' wins'), group('team-goals', 'Most Goals', row => row.stats.goals, ' goals'), group('clean', 'Most Clean Sheets', row => row.stats.cleanSheets, ' CS')] }, [teams, scoped]); return <Leaderboard groups={groups} /> }
function CombinationScope({ players, matches, filters, competition }: { players: Player[]; matches: Match[]; filters: RankingFilters; competition: CompetitionType | 'all' }) { const scoped = useMemo(() => scopedMatches(matches, filters, competition), [matches, filters, competition]); return <ApprovedCombinationRecords players={players} matches={scoped} /> }

function ApprovedCombinationRecords({ players, matches }: { players: Player[]; matches: Match[] }) {
  const groups = useMemo(() => {
    const pair = (ids: string[]) => ids.slice().sort().join(':')
    const direct = new Map<string, { ids: string[]; value: number }>(); const mutual = new Map<string, { ids: string[]; value: number }>(); const bothScored = new Map<string, { ids: string[]; value: number }>(); const bothGA = new Map<string, { ids: string[]; value: number }>()
    for (const match of matches) {
      const appearedForEventTeam = (playerId: string | undefined, teamId: string) => Boolean(playerId && match.appearances.some(appearance => appearance.playerId === playerId && appearance.teamId === teamId))
      const contributors = new Map<string, Set<string>>()
      for (const event of match.events) if (event.type === 'goal' && !event.ownGoal) { if (appearedForEventTeam(event.playerId, event.teamId)) contributors.set(event.playerId!, new Set([...(contributors.get(event.playerId!) ?? []), 'g'])); if (appearedForEventTeam(event.assistPlayerId, event.teamId)) contributors.set(event.assistPlayerId!, new Set([...(contributors.get(event.assistPlayerId!) ?? []), 'a'])); if (appearedForEventTeam(event.playerId, event.teamId) && appearedForEventTeam(event.assistPlayerId, event.teamId)) { const key = `${event.assistPlayerId}:${event.playerId}`; direct.set(key, { ids: [event.assistPlayerId!, event.playerId!], value: (direct.get(key)?.value ?? 0) + 1 }); const unordered = pair([event.assistPlayerId!, event.playerId!]); mutual.set(unordered, { ids: unordered.split(':'), value: (mutual.get(unordered)?.value ?? 0) + 1 }) } }
      const ids = [...contributors.keys()]; for (let left = 0; left < ids.length; left++) for (let right = left + 1; right < ids.length; right++) { const key = pair([ids[left], ids[right]]); if (contributors.get(ids[left])?.has('g') && contributors.get(ids[right])?.has('g')) bothScored.set(key, { ids: key.split(':'), value: (bothScored.get(key)?.value ?? 0) + 1 }); bothGA.set(key, { ids: key.split(':'), value: (bothGA.get(key)?.value ?? 0) + 1 }) }
    }
    const duo = combinationStats(players, matches, {}, 'duo').map(row => ({ ids: row.playerIds, value: row.combinedGA })); const cb = combinationStats(players, matches, {}, 'cb').filter(row => row.togetherMinutes >= 180).map(row => ({ ids: row.playerIds, value: row.weightedOpponentSot / (row.togetherMinutes / 90), minutes: row.togetherMinutes }))
    const entries = (rows: { ids: string[]; value: number; minutes?: number }[], ascending = false) => rows.filter(row => row.value > 0 || row.minutes).sort((left, right) => (ascending ? left.value - right.value : right.value - left.value) || pair(left.ids).localeCompare(pair(right.ids)))
    return [{ title: 'Most Goal Combinations', rows: entries([...direct.values()]), connector: '→' }, { title: 'Most Mutual Goal Combinations', rows: entries([...mutual.values()]), connector: '↔' }, { title: 'Most Matches Both Scored', rows: entries([...bothScored.values()]), connector: '+' }, { title: 'Most Matches Both Had G+A', rows: entries([...bothGA.values()]), connector: '+' }, { title: 'Best Duo Combined G+A', rows: entries(duo), connector: '+' }, { title: 'Best CB Partnership · Shot Suppression', rows: entries(cb, true), cb: true, connector: '+' }]
  }, [players, matches])
  const name = (ids: string[], connector: string) => ids.map(id => playerDisplayName(players.find(player => player.id === id))).join(` ${connector} `)
  const [expanded, setExpanded] = useState<string | null>(null)
  return <section aria-label="Approved combination records">{groups.map(group => { const rows = expanded === group.title ? group.rows : group.rows.slice(0, 3); const leader = rows[0]; const value = (row: typeof rows[number]) => group.cb ? `${row.value.toFixed(2)} SOT/90 · ${row.minutes}'` : String(row.value); return <section key={group.title} className="mb-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">{group.title}</h2>{group.rows.length > 3 && <button type="button" onClick={() => setExpanded(expanded === group.title ? null : group.title)} className="secondary-view-all">{expanded === group.title ? 'Show Less' : 'View All'}</button>}</div>{leader && <FirstPlaceHighlight name={name(leader.ids, group.connector)} detail={group.cb ? `${leader.minutes}' shared CB minutes` : 'Combination record leader'} value={value(leader)} />}<div className="overflow-hidden rounded-xl bg-zinc-900">{rows.slice(1).map((row, index) => <div key={`${group.title}:${combinationKey(row.ids)}`} className="grid min-h-11 grid-cols-[28px_1fr_auto] items-center gap-2 border-b border-white/5 px-3 text-xs last:border-0"><b className="text-zinc-500">#{index + 2}</b><span className="truncate font-semibold">{name(row.ids, group.connector)}</span><b className="text-emerald-300">{value(row)}</b></div>)}</div></section> })}</section>
}

export function CombinationSummary({ players, matches }: { players: Player[]; matches: Match[] }) {
  const leaders = useMemo(() => {
    const all = (kind: 'duo' | 'attack' | 'midfield' | 'cb') => combinationStats(players, matches, {}, kind)
    const best = (rows: ReturnType<typeof combinationStats>, metric: (row: ReturnType<typeof combinationStats>[number]) => number, ascending = false) => rows.slice().sort((left, right) => (ascending ? metric(left) - metric(right) : metric(right) - metric(left)) || right.startsTogether - left.startsTogether || left.key.localeCompare(right.key))[0]
    return [
      ['Best Attack', best(all('attack'), row => row.startingGoalsFor / Math.max(1, row.startsTogether))],
      ['Best Midfield', best(all('midfield'), row => (row.wins * 3 + row.draws) / Math.max(1, row.startsTogether))],
      ['Best Defense', best(all('cb'), row => row.startingGoalsAgainst / Math.max(1, row.startsTogether), true)],
      ['Best Pair', best(all('duo'), row => row.wins * 3 + row.draws)],
      ['Best Trio', best(all('attack'), row => row.startingGoalInvolvements)],
      ['Best Partnership', best(all('duo'), row => row.startingGoalInvolvements)],
    ] as const
  }, [players, matches])
  const name = (ids: string[]) => ids.map(id => playerFullName(players.find(player => player.id === id))).join(' · ')
  return <section className="mb-5" aria-label="Combination record leaders"><h2 className="mb-2 text-sm font-semibold">Combination Leaders</h2><div className="grid grid-cols-2 gap-2">{leaders.map(([label, row]) => <div key={label} className="rounded-xl bg-zinc-900 p-2 text-[10px]"><b className="block text-zinc-400">{label}</b><span className="mt-1 block truncate font-semibold">{row ? name(row.playerIds) : '—'}</span></div>)}</div></section>
}

function ExpandedTeamRecords({ teams, matches, filters, competition }: { teams: Team[]; matches: Match[]; filters: RankingFilters; competition: CompetitionType | 'all' }) {
  const scoped = useMemo(() => scopedMatches(matches, filters, competition), [matches, filters, competition])
  const groups = useMemo<Group[]>(() => {
    const rows = teams.map(team => {
      const summary = teamMetrics(team, scoped)
      const results = oldestMatches(summary.games).map(match => { const score = matchScore(match); const ours = match.homeTeamId === team.id ? score.home : score.away; const against = match.homeTeamId === team.id ? score.away : score.home; return { ours, against, outcome: ours > against ? 'W' : ours === against ? 'D' : 'L' } })
      const streak = (predicate: (result: typeof results[number]) => boolean) => results.reduce((best, _, end) => { let current = 0; for (let index = end; index >= 0 && predicate(results[index]); index--) current++; return Math.max(best, current) }, 0)
      return { team, summary, winRate: summary.games.length ? summary.wins / summary.games.length * 100 : 0, gfPerGame: summary.games.length ? summary.goals / summary.games.length : 0, gaPerGame: summary.games.length ? summary.conceded / summary.games.length : 0, gd: summary.goals - summary.conceded, gdPerGame: summary.games.length ? (summary.goals - summary.conceded) / summary.games.length : 0, scoring: streak(row => row.ours > 0), unbeaten: streak(row => row.outcome !== 'L'), winning: streak(row => row.outcome === 'W'), highFor: Math.max(0, ...results.map(row => row.ours)), highAgainst: Math.max(0, ...results.map(row => row.against)) }
    }).filter(row => row.summary.games.length)
    const group = (id: string, title: string, value: (row: typeof rows[number]) => number, suffix = '', decimals = false, ascending = false, format = (numeric: number) => decimals ? numeric.toFixed(2) : String(numeric)): Group => ({ id, title, rows: rank(rows.map(row => ({ id: row.team.id, name: row.team.name, numeric: ascending ? -value(row) : value(row), value: `${format(value(row))}${suffix}`, detail: `${row.summary.games.length} matches · ${row.summary.goals} GF / ${row.summary.conceded} GA` }))) })
    return [group('wins', 'Most Wins', row => row.summary.wins, ' wins'), group('win-rate', 'Highest Win Percentage', row => row.winRate, '%', true), group('goals', 'Most Goals', row => row.summary.goals, ' goals'), group('gf-rate', 'Highest GF per Match', row => row.gfPerGame, '', true), group('clean-sheets', 'Most Clean Sheets', row => row.summary.cleanSheets, ' CS'), group('ga-rate', 'Lowest Goals Conceded per Match', row => row.gaPerGame, '', true, true), group('scoring-streak', 'Longest Scoring Streak', row => row.scoring, ' matches'), group('unbeaten-streak', 'Longest Undefeated Streak', row => row.unbeaten, ' matches'), group('win-streak', 'Longest Winning Streak', row => row.winning, ' matches'), group('goal-difference', 'Best Goal Difference', row => row.gd, ' GD'), group('goal-difference-per-match', 'Best Goal Difference per Match', row => row.gdPerGame, '', true, false, formatSignedTwoDecimals), group('saves', 'Most Team Saves', row => row.summary.opponentSot - row.summary.conceded, ' saves'), group('high-score', 'Highest Score in One Match', row => row.highFor, ' goals'), group('high-conceded', 'Most Conceded in One Match', row => row.highAgainst, ' goals')]
  }, [teams, scoped])
  return <Leaderboard groups={groups} />
}

function FirstPlaceHighlight({ name, detail, value, onClick }: { name: string; detail: string; value: string; onClick?: () => void }) { const content = <><span className="text-xl">🥇</span><span className="min-w-0"><b className="block truncate">{name}</b><small className="block truncate text-zinc-400">{detail}</small></span><b className="text-amber-200">{value}</b></>; const className = "mb-2 grid w-full grid-cols-[auto_1fr_auto] items-center gap-3 rounded-2xl border border-amber-300/20 bg-gradient-to-r from-amber-300/15 to-zinc-900 p-3 text-left"; return onClick ? <button type="button" onClick={onClick} className={className}>{content}</button> : <div className={className}>{content}</div> }
function Leaderboard({ groups, onOpen, expanded: controlledExpanded, onExpanded }: { groups: Group[]; onOpen?: (id: string) => void; expanded?: string | null; onExpanded?: (id: string | null) => void }) {
  const [localExpanded, setLocalExpanded] = useState<string | null>(null)
  const expanded = controlledExpanded === undefined ? localExpanded : controlledExpanded
  const setExpanded = onExpanded ?? setLocalExpanded
  const activeGroup = expanded ? groups.find(group => group.id === expanded) : undefined
  const activeSectionId = activeGroup ? `records-leaderboard-${activeGroup.id}` : undefined
  return <div>
    {activeGroup && activeGroup.rows.length > 3 && <FloatingScrollToTop sectionId={activeSectionId} />}
    {groups.map(group => {
      const rows = expanded === group.id ? group.rows : group.rows.slice(0, 3)
      const leader = rows[0]
      return <section key={group.id} id={`records-leaderboard-${group.id}`} className="mb-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">{group.title}</h2>{group.rows.length > 3 && <button type="button" onClick={() => setExpanded(expanded === group.id ? null : group.id)} className="secondary-view-all">{expanded === group.id ? 'Show Less' : 'View All'}</button>}</div>{leader && <FirstPlaceHighlight name={leader.name} detail={leader.detail} value={leader.value} onClick={() => onOpen?.(leader.id)} />}<div className="overflow-hidden rounded-xl bg-zinc-900">{rows.slice(1).map(row => <button key={row.id} type="button" onClick={() => onOpen?.(row.id)} className="grid w-full grid-cols-[24px_1fr_auto] gap-2 border-b border-white/5 px-3 py-2.5 text-left text-xs last:border-0"><b className="text-zinc-500">#{row.rank}</b><span className="min-w-0"><b className="block truncate">{row.name}</b><small className="block truncate text-zinc-500">{row.detail}</small></span><b className="text-emerald-400">{row.value}</b></button>)}</div></section>
    })}
  </div>
}

export function AwardsRecords({ players, teams, matches, states, competition }: { players: Player[]; teams: Team[]; matches: Match[]; states: Parameters<typeof competitionHistory>[3]; competition: CompetitionType | 'all' }) {
  const tournamentTeams = useMemo(() => currentStaticTeams(teams), [teams])
  const seasons = useMemo(() => seasonsFromMatches(matches), [matches])
  const monthly = useMemo(() => seasons.flatMap(season => [...buildSeasonAnalytics(teams, players, matches, season).monthlyAwards.values()].flatMap(award => award.playerOfMonth ? [{ id: `${season}-${award.block.id}`, season, block: award.block.id, playerId: award.playerOfMonth.playerId }] : [])), [seasons, teams, players, matches])
  const playerName = (id: string) => playerFullName(players.find(player => player.id === id))
  return <section><h2 className="mb-2 text-lg font-semibold">Awards Hub</h2><p className="mb-3 text-[10px] text-zinc-500">Canonical finalized awards · {competition === 'all' ? 'All Competitions' : competition}</p>{(competition === 'all' || competition === 'league') && <section className="mb-5"><h3 className="mb-2 text-sm font-semibold">Player of the Month</h3><div className="space-y-1">{monthly.map(row => <div key={row.id} className="flex justify-between rounded-xl bg-zinc-900 px-3 py-2 text-xs"><b>{playerName(row.playerId)}</b><span className="text-zinc-400">{row.season}-{row.block}</span></div>)}{!monthly.length && <p className="text-xs text-zinc-500">No finalized monthly awards.</p>}</div></section>}{seasons.map(season => (competition === 'all' ? (['league', 'cup', 'champions'] as CompetitionType[]) : [competition]).map(type => { const award = awardsForCompetition(type, season, tournamentTeams, players, matches, states); return award.complete && award.mvp ? <div key={`${season}:${type}`} className="mb-2 rounded-xl bg-zinc-900 p-3 text-xs"><b>{season} · {type === 'league' ? 'League' : type === 'cup' ? 'Cup' : 'Champions'} Player of the Tournament</b><p className="mt-1 text-emerald-300">{playerName(award.mvp.playerId)} · {award.mvp.value.toFixed(2)}</p></div> : null }))}</section>
}

export function HistoryRecords({ players, teams, matches, states, competition: _competition }: { players: Player[]; teams: Team[]; matches: Match[]; states: Parameters<typeof competitionHistory>[3]; competition: CompetitionType | 'all' }) {
  const tournamentTeams = useMemo(() => currentStaticTeams(teams), [teams])
  const champions = useMemo(() => competitionHistory(tournamentTeams, matches, players, states), [tournamentTeams, matches, players, states])
  const history = useMemo(() => champions.map(entry => { const games = matches.filter(match => match.season === entry.season); const stats = buildGlobalRankingData(players, games, { seasons: [entry.season], teams: [], positions: [] }, 'rating'); const scorer = stats.slice().sort((a, b) => b.goals - a.goals)[0]; const assists = stats.slice().sort((a, b) => b.assists - a.assists)[0]; const rating = stats[0]; const mom = stats.slice().sort((a, b) => b.mom - a.mom)[0]; const xi = unifiedBestEleven(players, games, entry.season).slots.flatMap(slot => slot.playerId ? [playerFullName(players.find(player => player.id === slot.playerId))] : []); return { ...entry, scorer, assists, rating, mom, xi, awards: { league: awardsForCompetition('league', entry.season, tournamentTeams, players, matches, states), cup: awardsForCompetition('cup', entry.season, tournamentTeams, players, matches, states), champions: awardsForCompetition('champions', entry.season, tournamentTeams, players, matches, states), season: seasonAwards(entry.season, tournamentTeams, players, matches, states) } } }), [champions, matches, players, tournamentTeams, states])
  const trophies = useMemo(() => teams.map(team => { const league = champions.filter(row => row.league === team.id).length; const cup = champions.filter(row => row.cup === team.id).length; const championsTitles = champions.filter(row => row.champions === team.id).length; return { team, league, cup, champions: championsTitles, total: league + cup + championsTitles } }).filter(row => row.total).sort((a, b) => b.total - a.total), [teams, champions])
  const name = (id?: string) => id ? teams.find(team => team.id === id)?.name ?? '—' : '—'; const playerName = (id?: string) => id ? playerFullName(players.find(player => player.id === id)) : '—'
  return <><section className="mb-6"><h2 className="mb-2 text-sm font-semibold">Season History</h2><div className="space-y-3">{history.slice().reverse().map(row => <details key={row.season} className="rounded-2xl bg-zinc-900 p-3"><summary className="cursor-pointer text-sm font-black">🏆 {row.season} Awards</summary><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><Award label="👑 League Champion" value={name(row.league)} /><Award label="🥇 Cup Champion" value={name(row.cup)} /><Award label="🏆 Champions Champion" value={name(row.champions)} /><Award label="⚽ Golden Boot" value={`${playerName(row.scorer?.playerId)} · ${row.scorer?.goals ?? 0}`} /><Award label="🅰️ Assist Leader" value={`${playerName(row.assists?.playerId)} · ${row.assists?.assists ?? 0}`} /><Award label="🌟 Best Avg Rating" value={`${playerName(row.rating?.playerId)} · ${row.rating?.avgRating.toFixed(2) ?? '—'}`} /><Award label="MOM" value={`${playerName(row.mom?.playerId)} · ${row.mom?.mom ?? 0}`} /></div>{row.xi.length > 0 && <p className="mt-3 text-[10px] leading-relaxed text-zinc-400"><b className="text-zinc-200">Team of the Season:</b> {row.xi.join(', ')}</p>}</details>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">Trophy Cabinet</h2><div className="overflow-hidden rounded-xl bg-zinc-900">{trophies.map(row => <div key={row.team.id} className="grid grid-cols-[1fr_repeat(4,32px)] border-b border-white/5 px-3 py-2.5 text-[10px] last:border-0"><b className="truncate">{row.team.name}</b><span>👑{row.league}</span><span>🥇{row.cup}</span><span>🏆{row.champions}</span><b className="text-emerald-300">{row.total}</b></div>)}</div></section></>
}
function InsightsRecords({ season, players, teams, matches, onNavigate }: { season: string; players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) { const insights = useMemo(() => { const games = matches.filter(match => match.season === season); const teamRows = teams.map(team => ({ team, ...teamMetrics(team, games) })).filter(row => row.games.length).sort((a, b) => b.form.filter(result => result === 'W').length - a.form.filter(result => result === 'W').length).slice(0, 5); const playerRows = players.map(player => ({ player, form: playerForm(player, games) })).filter(row => row.form.ratings.length >= 3).sort((a, b) => b.form.last5Average - a.form.last5Average).slice(0, 5); return { teams: teamRows, players: playerRows } }, [teams, players, matches, season]); return <><section className="mb-6"><h2 className="mb-2 text-sm font-semibold">Team Form · {season}</h2><div className="grid gap-2">{insights.teams.map(row => <div key={row.team.id} className="rounded-xl bg-zinc-900 p-3"><div className="flex justify-between text-xs"><b>{row.team.name}</b><span className="tracking-widest">{row.form.join(' ')}</span></div><div className="mt-2 grid grid-cols-3 gap-1 text-center text-[10px]"><span>{(row.goals / row.games.length).toFixed(2)}<small className="block text-zinc-500">GF/M</small></span><span>{(row.conceded / row.games.length).toFixed(2)}<small className="block text-zinc-500">GA/M</small></span><span>{(row.opponentSot / row.games.length).toFixed(2)}<small className="block text-zinc-500">SOT/M</small></span></div></div>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">In-form Players</h2><div className="space-y-2">{insights.players.map(row => <button key={row.player.id} type="button" onClick={() => onNavigate({ name: 'player', id: row.player.id })} className="flex w-full justify-between rounded-xl bg-zinc-900 p-3 text-left text-xs"><b>{playerFullName(row.player)}</b><span className="text-emerald-300">Last 5 · {row.form.last5Average.toFixed(2)}</span></button>)}</div></section></> }
function IntegrityRecords({ players, teams, matches, onNavigate }: { players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) { const integrity = useMemo(() => auditDataIntegrity(matches, players, teams), [matches, players, teams]); return <section><div className="rounded-2xl bg-zinc-900 p-4"><h2 className="text-sm font-semibold">Data Integrity</h2><p className="mt-1 text-[10px] text-zinc-500">Read-only diagnostics. No football data is changed.</p><p className="mt-3 text-xs">{integrity.issues.length ? `${integrity.errors} errors · ${integrity.warnings} warnings` : '✓ No issues found.'}</p></div>{integrity.issues.length > 0 && <div className="mt-3 space-y-2">{integrity.issues.map((issue, index) => <div key={`${issue.matchId ?? 'global'}-${index}`} className="rounded-xl bg-zinc-900 p-3 text-xs"><div className="flex items-center justify-between gap-3"><b className={issue.severity === 'error' ? 'text-rose-300' : issue.severity === 'warning' ? 'text-amber-300' : 'text-sky-300'}>{issue.severity.toUpperCase()}</b>{issue.matchId && <button type="button" onClick={() => onNavigate({ name: 'match', id: issue.matchId! })} className="text-[10px] text-emerald-300">Open match</button>}</div><p className="mt-1 text-zinc-300">{issue.message}</p></div>)}</div>}</section> }
function Award({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-black/30 p-2"><small className="block text-zinc-500">{label}</small><b className="mt-1 block break-words">{value}</b></div> }
