import { useMemo } from 'react'
import { CompetitionScopeSelector } from '../components/CompetitionScopeSelector'
import { PlayerIdentityAction, TeamIdentityAction } from '../components/EntityActions'
import { CombinationPairIdentity } from '../components/CombinationPairIdentity'
import { PositionFilter } from '../components/PositionFilter'
import { TeamFilter } from '../components/TeamFilter'
import { RecordsSeasonFilter } from '../components/RecordsSeasonFilter'
import { CompactFilterMenu } from '../components/CompactFilterMenu'
import { matchCompetitionType } from '../engine/competition'
import { auditDataIntegrity } from '../engine/integrity'
import { playerForm } from '../engine/seasonInsights'
import { teamMetrics } from '../engine/teamMetrics'
import { seasonsFromMatches } from '../engine/stats'
import { playerFullName } from '../components/ui'
import { useStore } from '../store'
import type { CompetitionType, Match, Player, RecordsCategory, ScreenStateByView, Team, View } from '../types'
import { RecordsHistory } from './RecordsHistory'
import { emptyFilters, type RankingFilters } from './RankingFilters'
import { recordsLeaderboardGroups, type RecordsLeaderboardGroup, type RecordsLeaderboardKind, type RecordsLeaderboardRow } from './recordsLeaderboards'

type Category = RecordsCategory
const tabs: [Category, string, string][] = [['player', 'Player', '⚽'], ['combination', 'Combination', '🤝'], ['team', 'Team', '🛡️'], ['history', 'History', '🏆'], ['insights', 'Insights', '📈'], ['integrity', 'Data Integrity', '✓']]
const scopedMatches = (matches: Match[], filters: RankingFilters, competition: CompetitionType | 'all') => matches.filter(match => (!filters.seasons.length || filters.seasons.includes(match.season)) && (!filters.teams.length || filters.teams.includes(match.homeTeamId) || filters.teams.includes(match.awayTeamId)) && (competition === 'all' || matchCompetitionType(match) === competition))

export function RecordsScreen({ season, screenState, onStateChange, onNavigate }: { season: string; screenState: ScreenStateByView['records']; onStateChange: (state: ScreenStateByView['records']) => void; onNavigate: (view: View) => void }) {
  const { players, teams, matches, competitionStates = [] } = useStore()
  const { category, competition } = screenState
  const patchState = (patch: Partial<ScreenStateByView['records']>) => onStateChange({ ...screenState, ...patch })
  const filters: RankingFilters = { ...emptyFilters, seasons: screenState.filterSeasonIds, teams: screenState.filterTeamIds }
  const filtersApply = category === 'player' || category === 'combination' || category === 'team'
  const seasons = useMemo(() => seasonsFromMatches(matches), [matches])
  return <div className="px-4 pb-8 pt-6"><div className="mb-4 flex items-center justify-between gap-2"><div><h1 className="text-2xl font-semibold">Records</h1><p className="text-[10px] text-zinc-500">Leaders, partnerships and football history</p></div><div className="flex shrink-0 flex-wrap justify-end gap-1.5">{filtersApply && <RecordsSeasonFilter value={screenState.filterSeasonIds} seasons={seasons} onChange={filterSeasonIds => patchState({ filterSeasonIds })} />}{category === 'player' && <PositionFilter value={screenState.positionFilter} onChange={positionFilter => patchState({ positionFilter })} label="Player Records position" />}{filtersApply && <TeamFilter value={screenState.filterTeamIds[0] ?? null} teams={teams} onChange={teamId => patchState({ filterTeamIds: teamId ? [teamId] : [] })} label="Records team" />}</div></div><div className="sticky top-0 z-20 -mx-4 mb-3 border-y border-white/5 bg-black/95 px-4 py-2"><CompetitionScopeSelector value={competition} onChange={value => patchState({ competition: value })} /></div><div className="no-scrollbar mb-5 mt-3 flex gap-1 overflow-x-auto rounded-xl bg-zinc-900 p-1">{tabs.map(([id, label, icon]) => <button key={id} type="button" onClick={() => patchState({ category: id })} className={`shrink-0 rounded-lg px-3 py-2 text-[10px] font-bold ${category === id ? 'bg-emerald-500 text-black' : 'text-zinc-400'}`}><span aria-hidden="true">{icon}</span> {label}</button>)}</div>
    {(['player', 'combination', 'team'] as Category[]).includes(category) && <RecordsRankingPreviews category={category as RecordsLeaderboardKind} players={players} teams={teams} matches={matches} filters={filters} competition={competition} positionFilter={screenState.positionFilter} screenState={screenState} onSelectionChange={patchState} onNavigate={onNavigate} />}
    {category === 'history' && <RecordsHistory players={players} teams={teams} matches={matches} states={competitionStates} competition={competition} panel={screenState.historyPanel === 'awards' ? 'awards' : 'timeline'} openSeason={screenState.historySeason} openBlock={screenState.historyBlock} onPanel={panel => patchState({ historyPanel: panel, historyBlock: null })} onSeason={value => patchState({ historySeason: value, historyBlock: null })} onBlock={value => patchState({ historyBlock: value })} onPlayerOpen={id => onNavigate({ name: 'player', id })} />}
    {category === 'insights' && <InsightsRecords season={season} players={players} teams={teams} matches={scopedMatches(matches, filters, competition)} onNavigate={onNavigate} />}
    {category === 'integrity' && <IntegrityRecords players={players} teams={teams} matches={matches} onNavigate={onNavigate} />}
  </div>
}

function RecordsRankingPreviews({ category, players, teams, matches, filters, competition, positionFilter, screenState, onSelectionChange, onNavigate }: { category: RecordsLeaderboardKind; players: Player[]; teams: Team[]; matches: Match[]; filters: RankingFilters; competition: CompetitionType | 'all'; positionFilter: ScreenStateByView['records']['positionFilter']; screenState: ScreenStateByView['records']; onSelectionChange: (patch: Partial<ScreenStateByView['records']>) => void; onNavigate: (view: View) => void }) {
  const groups = useMemo(() => recordsLeaderboardGroups({ category, players, teams, matches, scope: { seasons: filters.seasons, teamIds: filters.teams, competition, positionFilter } }), [category, players, teams, matches, filters.seasons, filters.teams, competition, positionFilter])
  const playerById = useMemo(() => new Map(players.map(player => [player.id, player])), [players])
  const teamById = useMemo(() => new Map(teams.map(team => [team.id, team])), [teams])
  const card = (group: RecordsLeaderboardGroup) => <section key={group.id} className="mb-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">{group.title}</h2>{group.rows.length > 3 && <button type="button" onClick={() => onNavigate({ name: 'records-leaderboard', category, leaderboardId: group.id, competition, positionFilter, seasonIds: filters.seasons, teamIds: filters.teams })} className="secondary-view-all">View All</button>}</div><div className="overflow-hidden rounded-xl bg-zinc-900">{group.rows.slice(0, 3).map(row => <div key={row.id} className="grid min-h-11 grid-cols-[28px_1fr_auto] items-center gap-2 border-b border-white/5 px-3 text-xs last:border-0"><b className="text-zinc-500">#{row.rank}</b><RecordIdentity row={row} playerById={playerById} teamById={teamById} onNavigate={onNavigate} /><b className="text-emerald-300">{row.value}</b></div>)}</div></section>
  if (category !== 'combination') return <section aria-label="Records leaderboard previews">{groups.map(card)}</section>
  const selectedTogether = `together:${screenState.combinationPosition ?? 'attack'}:${screenState.combinationPlayers ?? 2}:${screenState.combinationMetric ?? 'starts'}`
  const bestGroups = groups.filter(group => group.id.startsWith('best-unit:'))
  const selectedBest = screenState.bestUnitId ?? 'best-unit:attack:2:goals'
  const choose = (label: string, value: string | number, options: { value: string | number; label: string }[], onChange: (value: string) => void) => <CompactFilterMenu value={String(value)} options={options.map(option => ({ value: String(option.value), label: option.label }))} onChange={onChange} label={`Combination ${label.toLowerCase()}`} menuClassName="max-h-64 overflow-y-auto overscroll-contain" popupAlign="start" />
  return <section aria-label="Records leaderboard previews">
    <h2 className="mb-3 text-base font-semibold">Goal Partnerships</h2>{groups.slice(0, 5).map(card)}
    <h2 className="mb-3 text-base font-semibold">Together</h2><div className="mb-3 flex flex-wrap gap-2">{choose('Position', screenState.combinationPosition ?? 'attack', [{ value: 'attack', label: 'Attack' }, { value: 'midfield', label: 'Midfield' }, { value: 'defence', label: 'Defence' }], value => onSelectionChange({ combinationPosition: value as 'attack' | 'midfield' | 'defence' }))}{choose('Players', screenState.combinationPlayers ?? 2, [2, 3, 4].map(value => ({ value, label: `${value} Players` })), value => onSelectionChange({ combinationPlayers: Number(value) as 2 | 3 | 4 }))}{choose('Metric', screenState.combinationMetric ?? 'starts', [{ value: 'starts', label: 'Starts' }, { value: 'minutes', label: 'Minutes' }, { value: 'ppg', label: 'PPG' }], value => onSelectionChange({ combinationMetric: value as 'starts' | 'minutes' | 'ppg' }))}</div>{groups.filter(group => group.id === selectedTogether).map(card)}
    <h2 className="mb-3 text-base font-semibold">Best Units</h2><div className="mb-3">{choose('Best unit', selectedBest, bestGroups.map(group => ({ value: group.id, label: group.title })), value => onSelectionChange({ bestUnitId: value }))}</div>{bestGroups.filter(group => group.id === selectedBest).map(card)}
    <h2 className="mb-3 text-base font-semibold">Defensive Partnerships</h2>{groups.filter(group => group.id === 'cb-suppression' || group.id === 'cb-ga').map(card)}
  </section>
}

function RecordIdentity({ row, playerById, teamById, onNavigate }: { row: RecordsLeaderboardRow; playerById: Map<string, Player>; teamById: Map<string, Team>; onNavigate: (view: View) => void }) {
  if (row.combinationPair) return <span className="min-w-0 overflow-hidden"><CombinationPairIdentity pair={row.combinationPair} playerById={playerById} onNavigate={onNavigate} />{row.detail !== 'Combination record' && <small className="block truncate text-[9px] text-zinc-500">{row.detail}</small>}</span>
  if (row.playerIds) return <span className="min-w-0 overflow-hidden"><span className="flex min-w-0 items-center gap-1 overflow-hidden">{row.playerIds.map(id => { const player = playerById.get(id); return <PlayerIdentityAction key={id} player={player} onNavigate={player ? playerId => onNavigate({ name: 'player', id: playerId }) : undefined} className="min-w-0 truncate text-left font-semibold" avatarClassName="hidden">{player?.displayName ?? player?.name ?? 'Unknown player'}</PlayerIdentityAction> })}</span><small className="block truncate text-[9px] text-zinc-500">{row.detail}</small></span>
  const team = teamById.get(row.id)
  if (team) return <TeamIdentityAction team={team} onNavigate={teamId => onNavigate({ name: 'team', id: teamId })} className="min-w-0 truncate text-left font-semibold">{team.name}</TeamIdentityAction>
  const player = playerById.get(row.id)
  return <PlayerIdentityAction player={player} onNavigate={player ? playerId => onNavigate({ name: 'player', id: playerId }) : undefined} className="min-w-0 truncate text-left font-semibold" avatarClassName="hidden">{row.name}</PlayerIdentityAction>
}

function InsightsRecords({ season, players, teams, matches, onNavigate }: { season: string; players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) {
  const insights = useMemo(() => { const games = matches.filter(match => match.season === season); const teamRows = teams.map(team => ({ team, ...teamMetrics(team, games) })).filter(row => row.games.length).sort((a, b) => b.form.filter(result => result === 'W').length - a.form.filter(result => result === 'W').length).slice(0, 5); const playerRows = players.map(player => ({ player, form: playerForm(player, games) })).filter(row => row.form.ratings.length >= 3).sort((a, b) => b.form.last5Average - a.form.last5Average).slice(0, 5); return { teams: teamRows, players: playerRows } }, [teams, players, matches, season])
  return <><section className="mb-6"><h2 className="mb-2 text-sm font-semibold">Team Form · {season}</h2><div className="grid gap-2">{insights.teams.map(row => <div key={row.team.id} className="rounded-xl bg-zinc-900 p-3"><div className="flex justify-between text-xs"><b>{row.team.name}</b><span className="tracking-widest">{row.form.join(' ')}</span></div><div className="mt-2 grid grid-cols-3 gap-1 text-center text-[10px]"><span>{(row.goals / row.games.length).toFixed(2)}<small className="block text-zinc-500">GF/M</small></span><span>{(row.conceded / row.games.length).toFixed(2)}<small className="block text-zinc-500">GA/M</small></span><span>{(row.opponentSot / row.games.length).toFixed(2)}<small className="block text-zinc-500">SOT/M</small></span></div></div>)}</div></section><section><h2 className="mb-2 text-sm font-semibold">In-form Players</h2><div className="space-y-2">{insights.players.map(row => <button key={row.player.id} type="button" onClick={() => onNavigate({ name: 'player', id: row.player.id })} className="flex w-full justify-between rounded-xl bg-zinc-900 p-3 text-left text-xs"><b>{playerFullName(row.player)}</b><span className="text-emerald-300">Last 5 · {row.form.last5Average.toFixed(2)}</span></button>)}</div></section></>
}

function IntegrityRecords({ players, teams, matches, onNavigate }: { players: Player[]; teams: Team[]; matches: Match[]; onNavigate: (view: View) => void }) { const integrity = useMemo(() => auditDataIntegrity(matches, players, teams), [matches, players, teams]); return <section><div className="rounded-2xl bg-zinc-900 p-4"><h2 className="text-sm font-semibold">Data Integrity</h2><p className="mt-1 text-[10px] text-zinc-500">Read-only diagnostics. No football data is changed.</p><p className="mt-3 text-xs">{integrity.issues.length ? `${integrity.errors} errors · ${integrity.warnings} warnings` : '✓ No issues found.'}</p></div>{integrity.issues.length > 0 && <div className="mt-3 space-y-2">{integrity.issues.map((issue, index) => <div key={`${issue.matchId ?? 'global'}-${index}`} className="rounded-xl bg-zinc-900 p-3 text-xs"><div className="flex items-center justify-between gap-3"><b className={issue.severity === 'error' ? 'text-rose-300' : issue.severity === 'warning' ? 'text-amber-300' : 'text-sky-300'}>{issue.severity.toUpperCase()}</b>{issue.matchId && <button type="button" onClick={() => onNavigate({ name: 'match', id: issue.matchId! })} className="text-[10px] text-emerald-300">Open match</button>}</div><p className="mt-1 text-zinc-300">{issue.message}</p></div>)}</div>}</section> }
